/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) USV_quat_ode_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[13] = {9, 1, 0, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[20] = {16, 1, 0, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};
static const casadi_int casadi_s3[13] = {11, 1, 0, 9, 2, 3, 4, 5, 6, 7, 8, 9, 10};

/* USV_quat_ode_expl_vde_adj:(i0[9],i1[9],i2[2],i3[16])->(o0[11x1,9nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real *w0=w+4, w1, w2, w3, w4, w5, *w6=w+13, *w7=w+17, *w8=w+21, *w9=w+25, *w10=w+29, *w11=w+45, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, *w23=w+65, w24, *w25=w+69, *w26=w+72, w27, w28, w29, w30, w31, w32, *w33=w+87, w34, w35, w36, w37, w38, w39, w40, w41, w42, w43, *w44=w+106;
  /* #0: @0 = zeros(4x1) */
  casadi_clear(w0, 4);
  /* #1: @1 = 0 */
  w1 = 0.;
  /* #2: @2 = 0 */
  w2 = 0.;
  /* #3: @3 = 0 */
  w3 = 0.;
  /* #4: @4 = input[0][8] */
  w4 = arg[0] ? arg[0][8] : 0;
  /* #5: @5 = (-@4) */
  w5 = (- w4 );
  /* #6: @6 = horzcat(@1, @2, @3, @5) */
  rr=w6;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w5;
  /* #7: @6 = @6' */
  /* #8: @1 = 0 */
  w1 = 0.;
  /* #9: @2 = 0 */
  w2 = 0.;
  /* #10: @3 = 0 */
  w3 = 0.;
  /* #11: @7 = horzcat(@1, @2, @4, @3) */
  rr=w7;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w4;
  *rr++ = w3;
  /* #12: @7 = @7' */
  /* #13: @1 = 0 */
  w1 = 0.;
  /* #14: @2 = (-@4) */
  w2 = (- w4 );
  /* #15: @3 = 0 */
  w3 = 0.;
  /* #16: @5 = 0 */
  w5 = 0.;
  /* #17: @8 = horzcat(@1, @2, @3, @5) */
  rr=w8;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w5;
  /* #18: @8 = @8' */
  /* #19: @1 = 0 */
  w1 = 0.;
  /* #20: @2 = 0 */
  w2 = 0.;
  /* #21: @3 = 0 */
  w3 = 0.;
  /* #22: @9 = horzcat(@4, @1, @2, @3) */
  rr=w9;
  *rr++ = w4;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w3;
  /* #23: @9 = @9' */
  /* #24: @10 = horzcat(@6, @7, @8, @9) */
  rr=w10;
  for (i=0, cs=w6; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w7; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w8; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w9; i<4; ++i) *rr++ = *cs++;
  /* #25: @1 = 0.5 */
  w1 = 5.0000000000000000e-01;
  /* #26: @11 = input[1][0] */
  casadi_copy(arg[1], 9, w11);
  /* #27: {@2, @3, @6, @5, @12, @13} = vertsplit(@11) */
  w2 = w11[0];
  w3 = w11[1];
  casadi_copy(w11+2, 4, w6);
  w5 = w11[6];
  w12 = w11[7];
  w13 = w11[8];
  /* #28: @6 = (@1*@6) */
  for (i=0, rr=w6, cs=w6; i<4; ++i) (*rr++)  = (w1*(*cs++));
  /* #29: @0 = mac(@10,@6,@0) */
  for (i=0, rr=w0; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w10+j, tt=w6+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #30: {@1, @14, @15, @16} = vertsplit(@0) */
  w1 = w0[0];
  w14 = w0[1];
  w15 = w0[2];
  w16 = w0[3];
  /* #31: @17 = input[0][3] */
  w17 = arg[0] ? arg[0][3] : 0;
  /* #32: @18 = input[0][2] */
  w18 = arg[0] ? arg[0][2] : 0;
  /* #33: @19 = sq(@18) */
  w19 = casadi_sq( w18 );
  /* #34: @20 = sq(@17) */
  w20 = casadi_sq( w17 );
  /* #35: @19 = (@19+@20) */
  w19 += w20;
  /* #36: @20 = input[0][4] */
  w20 = arg[0] ? arg[0][4] : 0;
  /* #37: @21 = sq(@20) */
  w21 = casadi_sq( w20 );
  /* #38: @19 = (@19+@21) */
  w19 += w21;
  /* #39: @21 = input[0][5] */
  w21 = arg[0] ? arg[0][5] : 0;
  /* #40: @22 = sq(@21) */
  w22 = casadi_sq( w21 );
  /* #41: @19 = (@19+@22) */
  w19 += w22;
  /* #42: @19 = sqrt(@19) */
  w19 = sqrt( w19 );
  /* #43: @22 = (@17/@19) */
  w22  = (w17/w19);
  /* #44: @11 = zeros(3x3) */
  casadi_clear(w11, 9);
  /* #45: @23 = zeros(3x1) */
  casadi_clear(w23, 3);
  /* #46: (@23[1] += @3) */
  for (rr=w23+1, ss=(&w3); rr!=w23+2; rr+=1) *rr += *ss++;
  /* #47: (@23[0] += @2) */
  for (rr=w23+0, ss=(&w2); rr!=w23+1; rr+=1) *rr += *ss++;
  /* #48: @2 = input[0][6] */
  w2 = arg[0] ? arg[0][6] : 0;
  /* #49: @3 = input[0][7] */
  w3 = arg[0] ? arg[0][7] : 0;
  /* #50: @24 = 0 */
  w24 = 0.;
  /* #51: @25 = vertcat(@2, @3, @24) */
  rr=w25;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w24;
  /* #52: @25 = @25' */
  /* #53: @11 = mac(@23,@25,@11) */
  for (i=0, rr=w11; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w23+j, tt=w25+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #54: @24 = 0 */
  w24 = 0.;
  /* #55: @26 = @11; (@26[8] = @24) */
  casadi_copy(w11, 9, w26);
  for (rr=w26+8, ss=(&w24); rr!=w26+9; rr+=1) *rr = *ss++;
  /* #56: @24 = @26[5] */
  for (rr=(&w24), ss=w26+5; ss!=w26+6; ss+=1) *rr++ = *ss;
  /* #57: @24 = (2.*@24) */
  w24 = (2.* w24 );
  /* #58: @27 = (@22*@24) */
  w27  = (w22*w24);
  /* #59: @28 = (@20/@19) */
  w28  = (w20/w19);
  /* #60: @29 = 0 */
  w29 = 0.;
  /* #61: (@26[5] = @29) */
  for (rr=w26+5, ss=(&w29); rr!=w26+6; rr+=1) *rr = *ss++;
  /* #62: @29 = @26[2] */
  for (rr=(&w29), ss=w26+2; ss!=w26+3; ss+=1) *rr++ = *ss;
  /* #63: @29 = (2.*@29) */
  w29 = (2.* w29 );
  /* #64: @30 = (@28*@29) */
  w30  = (w28*w29);
  /* #65: @27 = (@27-@30) */
  w27 -= w30;
  /* #66: @30 = 0 */
  w30 = 0.;
  /* #67: (@26[2] = @30) */
  for (rr=w26+2, ss=(&w30); rr!=w26+3; rr+=1) *rr = *ss++;
  /* #68: @30 = @26[7] */
  for (rr=(&w30), ss=w26+7; ss!=w26+8; ss+=1) *rr++ = *ss;
  /* #69: @30 = (2.*@30) */
  w30 = (2.* w30 );
  /* #70: @31 = (@22*@30) */
  w31  = (w22*w30);
  /* #71: @27 = (@27-@31) */
  w27 -= w31;
  /* #72: @31 = (@21/@19) */
  w31  = (w21/w19);
  /* #73: @32 = 0 */
  w32 = 0.;
  /* #74: (@26[7] = @32) */
  for (rr=w26+7, ss=(&w32); rr!=w26+8; rr+=1) *rr = *ss++;
  /* #75: @32 = 0 */
  w32 = 0.;
  /* #76: @33 = @26; (@33[4] = @32) */
  casadi_copy(w26, 9, w33);
  for (rr=w33+4, ss=(&w32); rr!=w33+5; rr+=1) *rr = *ss++;
  /* #77: @32 = @33[1] */
  for (rr=(&w32), ss=w33+1; ss!=w33+2; ss+=1) *rr++ = *ss;
  /* #78: @32 = (2.*@32) */
  w32 = (2.* w32 );
  /* #79: @34 = (@31*@32) */
  w34  = (w31*w32);
  /* #80: @27 = (@27+@34) */
  w27 += w34;
  /* #81: @34 = 0 */
  w34 = 0.;
  /* #82: (@33[1] = @34) */
  for (rr=w33+1, ss=(&w34); rr!=w33+2; rr+=1) *rr = *ss++;
  /* #83: @34 = @33[6] */
  for (rr=(&w34), ss=w33+6; ss!=w33+7; ss+=1) *rr++ = *ss;
  /* #84: @34 = (2.*@34) */
  w34 = (2.* w34 );
  /* #85: @35 = (@28*@34) */
  w35  = (w28*w34);
  /* #86: @27 = (@27+@35) */
  w27 += w35;
  /* #87: @35 = 0 */
  w35 = 0.;
  /* #88: (@33[6] = @35) */
  for (rr=w33+6, ss=(&w35); rr!=w33+7; rr+=1) *rr = *ss++;
  /* #89: @35 = @33[3] */
  for (rr=(&w35), ss=w33+3; ss!=w33+4; ss+=1) *rr++ = *ss;
  /* #90: @35 = (2.*@35) */
  w35 = (2.* w35 );
  /* #91: @36 = (@31*@35) */
  w36  = (w31*w35);
  /* #92: @27 = (@27-@36) */
  w27 -= w36;
  /* #93: @36 = (@27/@19) */
  w36  = (w27/w19);
  /* #94: @1 = (@1+@36) */
  w1 += w36;
  /* #95: @36 = (2.*@18) */
  w36 = (2.* w18 );
  /* #96: @37 = (@22/@19) */
  w37  = (w22/w19);
  /* #97: @38 = (2.*@22) */
  w38 = (2.* w22 );
  /* #98: @39 = @11[8] */
  for (rr=(&w39), ss=w11+8; ss!=w11+9; ss+=1) *rr++ = *ss;
  /* #99: @39 = (-@39) */
  w39 = (- w39 );
  /* #100: @39 = (2.*@39) */
  w39 = (2.* w39 );
  /* #101: @38 = (@38*@39) */
  w38 *= w39;
  /* #102: @40 = (@18/@19) */
  w40  = (w18/w19);
  /* #103: @41 = (@40*@24) */
  w41  = (w40*w24);
  /* #104: @38 = (@38+@41) */
  w38 += w41;
  /* #105: @41 = (@31*@29) */
  w41  = (w31*w29);
  /* #106: @38 = (@38+@41) */
  w38 += w41;
  /* #107: @41 = (@40*@30) */
  w41  = (w40*w30);
  /* #108: @38 = (@38-@41) */
  w38 -= w41;
  /* #109: @41 = (2.*@22) */
  w41 = (2.* w22 );
  /* #110: @42 = @26[4] */
  for (rr=(&w42), ss=w26+4; ss!=w26+5; ss+=1) *rr++ = *ss;
  /* #111: @42 = (-@42) */
  w42 = (- w42 );
  /* #112: @42 = (2.*@42) */
  w42 = (2.* w42 );
  /* #113: @41 = (@41*@42) */
  w41 *= w42;
  /* #114: @38 = (@38+@41) */
  w38 += w41;
  /* #115: @41 = (@28*@32) */
  w41  = (w28*w32);
  /* #116: @38 = (@38+@41) */
  w38 += w41;
  /* #117: @41 = (@31*@34) */
  w41  = (w31*w34);
  /* #118: @38 = (@38+@41) */
  w38 += w41;
  /* #119: @41 = (@28*@35) */
  w41  = (w28*w35);
  /* #120: @38 = (@38+@41) */
  w38 += w41;
  /* #121: @37 = (@37*@38) */
  w37 *= w38;
  /* #122: @37 = (-@37) */
  w37 = (- w37 );
  /* #123: @41 = (@40/@19) */
  w41  = (w40/w19);
  /* #124: @41 = (@41*@27) */
  w41 *= w27;
  /* #125: @37 = (@37-@41) */
  w37 -= w41;
  /* #126: @41 = (@31/@19) */
  w41  = (w31/w19);
  /* #127: @27 = (@28*@24) */
  w27  = (w28*w24);
  /* #128: @43 = (@22*@29) */
  w43  = (w22*w29);
  /* #129: @27 = (@27+@43) */
  w27 += w43;
  /* #130: @43 = (@28*@30) */
  w43  = (w28*w30);
  /* #131: @27 = (@27+@43) */
  w27 += w43;
  /* #132: @43 = (2.*@31) */
  w43 = (2.* w31 );
  /* #133: @43 = (@43*@42) */
  w43 *= w42;
  /* #134: @27 = (@27+@43) */
  w27 += w43;
  /* #135: @43 = (@40*@32) */
  w43  = (w40*w32);
  /* #136: @27 = (@27+@43) */
  w27 += w43;
  /* #137: @43 = (@22*@34) */
  w43  = (w22*w34);
  /* #138: @27 = (@27+@43) */
  w27 += w43;
  /* #139: @43 = (@40*@35) */
  w43  = (w40*w35);
  /* #140: @27 = (@27-@43) */
  w27 -= w43;
  /* #141: @43 = (2.*@31) */
  w43 = (2.* w31 );
  /* #142: @42 = 0 */
  w42 = 0.;
  /* #143: (@33[3] = @42) */
  for (rr=w33+3, ss=(&w42); rr!=w33+4; rr+=1) *rr = *ss++;
  /* #144: @42 = @33[0] */
  for (rr=(&w42), ss=w33+0; ss!=w33+1; ss+=1) *rr++ = *ss;
  /* #145: @42 = (-@42) */
  w42 = (- w42 );
  /* #146: @42 = (2.*@42) */
  w42 = (2.* w42 );
  /* #147: @43 = (@43*@42) */
  w43 *= w42;
  /* #148: @27 = (@27+@43) */
  w27 += w43;
  /* #149: @41 = (@41*@27) */
  w41 *= w27;
  /* #150: @37 = (@37-@41) */
  w37 -= w41;
  /* #151: @41 = (@28/@19) */
  w41  = (w28/w19);
  /* #152: @43 = (2.*@28) */
  w43 = (2.* w28 );
  /* #153: @43 = (@43*@39) */
  w43 *= w39;
  /* #154: @24 = (@31*@24) */
  w24  = (w31*w24);
  /* #155: @43 = (@43+@24) */
  w43 += w24;
  /* #156: @29 = (@40*@29) */
  w29  = (w40*w29);
  /* #157: @43 = (@43-@29) */
  w43 -= w29;
  /* #158: @30 = (@31*@30) */
  w30  = (w31*w30);
  /* #159: @43 = (@43+@30) */
  w43 += w30;
  /* #160: @32 = (@22*@32) */
  w32  = (w22*w32);
  /* #161: @43 = (@43+@32) */
  w43 += w32;
  /* #162: @34 = (@40*@34) */
  w34  = (w40*w34);
  /* #163: @43 = (@43+@34) */
  w43 += w34;
  /* #164: @35 = (@22*@35) */
  w35  = (w22*w35);
  /* #165: @43 = (@43+@35) */
  w43 += w35;
  /* #166: @35 = (2.*@28) */
  w35 = (2.* w28 );
  /* #167: @35 = (@35*@42) */
  w35 *= w42;
  /* #168: @43 = (@43+@35) */
  w43 += w35;
  /* #169: @41 = (@41*@43) */
  w41 *= w43;
  /* #170: @37 = (@37-@41) */
  w37 -= w41;
  /* #171: @41 = (2.*@19) */
  w41 = (2.* w19 );
  /* #172: @37 = (@37/@41) */
  w37 /= w41;
  /* #173: @36 = (@36*@37) */
  w36 *= w37;
  /* #174: @1 = (@1+@36) */
  w1 += w36;
  /* #175: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  /* #176: @38 = (@38/@19) */
  w38 /= w19;
  /* #177: @14 = (@14+@38) */
  w14 += w38;
  /* #178: @38 = (2.*@17) */
  w38 = (2.* w17 );
  /* #179: @38 = (@38*@37) */
  w38 *= w37;
  /* #180: @14 = (@14+@38) */
  w14 += w38;
  /* #181: output[0][1] = @14 */
  if (res[0]) res[0][1] = w14;
  /* #182: @43 = (@43/@19) */
  w43 /= w19;
  /* #183: @15 = (@15+@43) */
  w15 += w43;
  /* #184: @43 = (2.*@20) */
  w43 = (2.* w20 );
  /* #185: @43 = (@43*@37) */
  w43 *= w37;
  /* #186: @15 = (@15+@43) */
  w15 += w43;
  /* #187: output[0][2] = @15 */
  if (res[0]) res[0][2] = w15;
  /* #188: @27 = (@27/@19) */
  w27 /= w19;
  /* #189: @16 = (@16+@27) */
  w16 += w27;
  /* #190: @27 = (2.*@21) */
  w27 = (2.* w21 );
  /* #191: @27 = (@27*@37) */
  w27 *= w37;
  /* #192: @16 = (@16+@27) */
  w16 += w27;
  /* #193: output[0][3] = @16 */
  if (res[0]) res[0][3] = w16;
  /* #194: @16 = 0.3 */
  w16 = 2.9999999999999999e-01;
  /* #195: @27 = 0.0952381 */
  w27 = 9.5238095238095233e-02;
  /* #196: @27 = (@27*@5) */
  w27 *= w5;
  /* #197: @16 = (@16*@27) */
  w16 *= w27;
  /* #198: @16 = (-@16) */
  w16 = (- w16 );
  /* #199: @5 = 10 */
  w5 = 10.;
  /* #200: @37 = 0.0769231 */
  w37 = 7.6923076923076927e-02;
  /* #201: @37 = (@37*@12) */
  w37 *= w12;
  /* #202: @12 = (@4*@37) */
  w12  = (w4*w37);
  /* #203: @12 = (@5*@12) */
  w12  = (w5*w12);
  /* #204: @16 = (@16-@12) */
  w16 -= w12;
  /* #205: @25 = zeros(3x1) */
  casadi_clear(w25, 3);
  /* #206: @33 = zeros(3x3) */
  casadi_clear(w33, 9);
  /* #207: @12 = 1 */
  w12 = 1.;
  /* #208: @19 = sq(@28) */
  w19 = casadi_sq( w28 );
  /* #209: @15 = sq(@31) */
  w15 = casadi_sq( w31 );
  /* #210: @19 = (@19+@15) */
  w19 += w15;
  /* #211: @19 = (2.*@19) */
  w19 = (2.* w19 );
  /* #212: @12 = (@12-@19) */
  w12 -= w19;
  /* #213: (@33[0] = @12) */
  for (rr=w33+0, ss=(&w12); rr!=w33+1; rr+=1) *rr = *ss++;
  /* #214: @12 = (@22*@28) */
  w12  = (w22*w28);
  /* #215: @19 = (@40*@31) */
  w19  = (w40*w31);
  /* #216: @12 = (@12-@19) */
  w12 -= w19;
  /* #217: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #218: (@33[3] = @12) */
  for (rr=w33+3, ss=(&w12); rr!=w33+4; rr+=1) *rr = *ss++;
  /* #219: @12 = (@22*@31) */
  w12  = (w22*w31);
  /* #220: @19 = (@40*@28) */
  w19  = (w40*w28);
  /* #221: @12 = (@12+@19) */
  w12 += w19;
  /* #222: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #223: (@33[6] = @12) */
  for (rr=w33+6, ss=(&w12); rr!=w33+7; rr+=1) *rr = *ss++;
  /* #224: @12 = (@22*@28) */
  w12  = (w22*w28);
  /* #225: @19 = (@40*@31) */
  w19  = (w40*w31);
  /* #226: @12 = (@12+@19) */
  w12 += w19;
  /* #227: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #228: (@33[1] = @12) */
  for (rr=w33+1, ss=(&w12); rr!=w33+2; rr+=1) *rr = *ss++;
  /* #229: @12 = 1 */
  w12 = 1.;
  /* #230: @19 = sq(@22) */
  w19 = casadi_sq( w22 );
  /* #231: @15 = sq(@31) */
  w15 = casadi_sq( w31 );
  /* #232: @19 = (@19+@15) */
  w19 += w15;
  /* #233: @19 = (2.*@19) */
  w19 = (2.* w19 );
  /* #234: @12 = (@12-@19) */
  w12 -= w19;
  /* #235: (@33[4] = @12) */
  for (rr=w33+4, ss=(&w12); rr!=w33+5; rr+=1) *rr = *ss++;
  /* #236: @12 = (@28*@31) */
  w12  = (w28*w31);
  /* #237: @19 = (@40*@22) */
  w19  = (w40*w22);
  /* #238: @12 = (@12-@19) */
  w12 -= w19;
  /* #239: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #240: (@33[7] = @12) */
  for (rr=w33+7, ss=(&w12); rr!=w33+8; rr+=1) *rr = *ss++;
  /* #241: @12 = (@22*@31) */
  w12  = (w22*w31);
  /* #242: @19 = (@40*@28) */
  w19  = (w40*w28);
  /* #243: @12 = (@12-@19) */
  w12 -= w19;
  /* #244: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #245: (@33[2] = @12) */
  for (rr=w33+2, ss=(&w12); rr!=w33+3; rr+=1) *rr = *ss++;
  /* #246: @31 = (@28*@31) */
  w31  = (w28*w31);
  /* #247: @40 = (@40*@22) */
  w40 *= w22;
  /* #248: @31 = (@31+@40) */
  w31 += w40;
  /* #249: @31 = (2.*@31) */
  w31 = (2.* w31 );
  /* #250: (@33[5] = @31) */
  for (rr=w33+5, ss=(&w31); rr!=w33+6; rr+=1) *rr = *ss++;
  /* #251: @31 = 1 */
  w31 = 1.;
  /* #252: @22 = sq(@22) */
  w22 = casadi_sq( w22 );
  /* #253: @28 = sq(@28) */
  w28 = casadi_sq( w28 );
  /* #254: @22 = (@22+@28) */
  w22 += w28;
  /* #255: @22 = (2.*@22) */
  w22 = (2.* w22 );
  /* #256: @31 = (@31-@22) */
  w31 -= w22;
  /* #257: (@33[8] = @31) */
  for (rr=w33+8, ss=(&w31); rr!=w33+9; rr+=1) *rr = *ss++;
  /* #258: @26 = @33' */
  for (i=0, rr=w26, cs=w33; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #259: @25 = mac(@26,@23,@25) */
  for (i=0, rr=w25; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w26+j, tt=w23+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #260: {@31, @22, NULL} = vertsplit(@25) */
  w31 = w25[0];
  w22 = w25[1];
  /* #261: @16 = (@16+@31) */
  w16 += w31;
  /* #262: output[0][4] = @16 */
  if (res[0]) res[0][4] = w16;
  /* #263: @16 = -1.5 */
  w16 = -1.5000000000000000e+00;
  /* #264: @16 = (@16*@37) */
  w16 *= w37;
  /* #265: @31 = 10 */
  w31 = 10.;
  /* #266: @4 = (@4*@27) */
  w4 *= w27;
  /* #267: @4 = (@31*@4) */
  w4  = (w31*w4);
  /* #268: @16 = (@16+@4) */
  w16 += w4;
  /* #269: @16 = (@16+@22) */
  w16 += w22;
  /* #270: output[0][5] = @16 */
  if (res[0]) res[0][5] = w16;
  /* #271: @5 = (@5*@2) */
  w5 *= w2;
  /* #272: @5 = (@5*@37) */
  w5 *= w37;
  /* #273: @5 = (-@5) */
  w5 = (- w5 );
  /* #274: @37 = 0.2 */
  w37 = 2.0000000000000001e-01;
  /* #275: @2 = 0.379747 */
  w2 = 3.7974683544303789e-01;
  /* #276: @2 = (@2*@13) */
  w2 *= w13;
  /* #277: @37 = (@37*@2) */
  w37 *= w2;
  /* #278: @5 = (@5-@37) */
  w5 -= w37;
  /* #279: @31 = (@31*@3) */
  w31 *= w3;
  /* #280: @31 = (@31*@27) */
  w31 *= w27;
  /* #281: @5 = (@5+@31) */
  w5 += w31;
  /* #282: @10 = zeros(4x4) */
  casadi_clear(w10, 16);
  /* #283: @0 = vertcat(@18, @17, @20, @21) */
  rr=w0;
  *rr++ = w18;
  *rr++ = w17;
  *rr++ = w20;
  *rr++ = w21;
  /* #284: @0 = @0' */
  /* #285: @10 = mac(@6,@0,@10) */
  for (i=0, rr=w10; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w6+j, tt=w0+i*1; k<1; ++k) *rr += ss[k*4]**tt++;
  /* #286: @44 = @10' */
  for (i=0, rr=w44, cs=w10; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #287: {@6, @0, @7, @8} = horzsplit(@44) */
  casadi_copy(w44, 4, w6);
  casadi_copy(w44+4, 4, w0);
  casadi_copy(w44+8, 4, w7);
  casadi_copy(w44+12, 4, w8);
  /* #288: @8 = @8' */
  /* #289: {@18, NULL, NULL, NULL} = horzsplit(@8) */
  w18 = w8[0];
  /* #290: @5 = (@5+@18) */
  w5 += w18;
  /* #291: @7 = @7' */
  /* #292: {NULL, @18, NULL, NULL} = horzsplit(@7) */
  w18 = w7[1];
  /* #293: @5 = (@5-@18) */
  w5 -= w18;
  /* #294: @0 = @0' */
  /* #295: {NULL, NULL, @18, NULL} = horzsplit(@0) */
  w18 = w0[2];
  /* #296: @5 = (@5+@18) */
  w5 += w18;
  /* #297: @6 = @6' */
  /* #298: {NULL, NULL, NULL, @18} = horzsplit(@6) */
  w18 = w6[3];
  /* #299: @5 = (@5-@18) */
  w5 -= w18;
  /* #300: output[0][6] = @5 */
  if (res[0]) res[0][6] = w5;
  /* #301: output[0][7] = @27 */
  if (res[0]) res[0][7] = w27;
  /* #302: output[0][8] = @2 */
  if (res[0]) res[0][8] = w2;
  return 0;
}

CASADI_SYMBOL_EXPORT int USV_quat_ode_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int USV_quat_ode_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int USV_quat_ode_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void USV_quat_ode_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int USV_quat_ode_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void USV_quat_ode_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void USV_quat_ode_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void USV_quat_ode_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int USV_quat_ode_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int USV_quat_ode_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real USV_quat_ode_expl_vde_adj_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* USV_quat_ode_expl_vde_adj_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* USV_quat_ode_expl_vde_adj_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* USV_quat_ode_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* USV_quat_ode_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int USV_quat_ode_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 7;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 122;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
