/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) USV_quat_ode_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[13] = {9, 1, 0, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[20] = {16, 1, 0, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};

/* USV_quat_ode_expl_ode_fun:(i0[9],i1[2],i2[16])->(o0[9]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real *w0=w+4, *w1=w+7, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, *w13=w+27, *w14=w+30, w15, *w16=w+35, *w17=w+39, *w18=w+43, *w19=w+47, *w20=w+51, *w21=w+67;
  /* #0: @0 = zeros(3x1) */
  casadi_clear(w0, 3);
  /* #1: @1 = zeros(3x3) */
  casadi_clear(w1, 9);
  /* #2: @2 = 1 */
  w2 = 1.;
  /* #3: @3 = input[0][4] */
  w3 = arg[0] ? arg[0][4] : 0;
  /* #4: @4 = input[0][2] */
  w4 = arg[0] ? arg[0][2] : 0;
  /* #5: @5 = sq(@4) */
  w5 = casadi_sq( w4 );
  /* #6: @6 = input[0][3] */
  w6 = arg[0] ? arg[0][3] : 0;
  /* #7: @7 = sq(@6) */
  w7 = casadi_sq( w6 );
  /* #8: @5 = (@5+@7) */
  w5 += w7;
  /* #9: @7 = sq(@3) */
  w7 = casadi_sq( w3 );
  /* #10: @5 = (@5+@7) */
  w5 += w7;
  /* #11: @7 = input[0][5] */
  w7 = arg[0] ? arg[0][5] : 0;
  /* #12: @8 = sq(@7) */
  w8 = casadi_sq( w7 );
  /* #13: @5 = (@5+@8) */
  w5 += w8;
  /* #14: @5 = sqrt(@5) */
  w5 = sqrt( w5 );
  /* #15: @8 = (@3/@5) */
  w8  = (w3/w5);
  /* #16: @9 = sq(@8) */
  w9 = casadi_sq( w8 );
  /* #17: @10 = (@7/@5) */
  w10  = (w7/w5);
  /* #18: @11 = sq(@10) */
  w11 = casadi_sq( w10 );
  /* #19: @9 = (@9+@11) */
  w9 += w11;
  /* #20: @9 = (2.*@9) */
  w9 = (2.* w9 );
  /* #21: @2 = (@2-@9) */
  w2 -= w9;
  /* #22: (@1[0] = @2) */
  for (rr=w1+0, ss=(&w2); rr!=w1+1; rr+=1) *rr = *ss++;
  /* #23: @2 = (@6/@5) */
  w2  = (w6/w5);
  /* #24: @9 = (@2*@8) */
  w9  = (w2*w8);
  /* #25: @5 = (@4/@5) */
  w5  = (w4/w5);
  /* #26: @11 = (@5*@10) */
  w11  = (w5*w10);
  /* #27: @9 = (@9-@11) */
  w9 -= w11;
  /* #28: @9 = (2.*@9) */
  w9 = (2.* w9 );
  /* #29: (@1[3] = @9) */
  for (rr=w1+3, ss=(&w9); rr!=w1+4; rr+=1) *rr = *ss++;
  /* #30: @9 = (@2*@10) */
  w9  = (w2*w10);
  /* #31: @11 = (@5*@8) */
  w11  = (w5*w8);
  /* #32: @9 = (@9+@11) */
  w9 += w11;
  /* #33: @9 = (2.*@9) */
  w9 = (2.* w9 );
  /* #34: (@1[6] = @9) */
  for (rr=w1+6, ss=(&w9); rr!=w1+7; rr+=1) *rr = *ss++;
  /* #35: @9 = (@2*@8) */
  w9  = (w2*w8);
  /* #36: @11 = (@5*@10) */
  w11  = (w5*w10);
  /* #37: @9 = (@9+@11) */
  w9 += w11;
  /* #38: @9 = (2.*@9) */
  w9 = (2.* w9 );
  /* #39: (@1[1] = @9) */
  for (rr=w1+1, ss=(&w9); rr!=w1+2; rr+=1) *rr = *ss++;
  /* #40: @9 = 1 */
  w9 = 1.;
  /* #41: @11 = sq(@2) */
  w11 = casadi_sq( w2 );
  /* #42: @12 = sq(@10) */
  w12 = casadi_sq( w10 );
  /* #43: @11 = (@11+@12) */
  w11 += w12;
  /* #44: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #45: @9 = (@9-@11) */
  w9 -= w11;
  /* #46: (@1[4] = @9) */
  for (rr=w1+4, ss=(&w9); rr!=w1+5; rr+=1) *rr = *ss++;
  /* #47: @9 = (@8*@10) */
  w9  = (w8*w10);
  /* #48: @11 = (@5*@2) */
  w11  = (w5*w2);
  /* #49: @9 = (@9-@11) */
  w9 -= w11;
  /* #50: @9 = (2.*@9) */
  w9 = (2.* w9 );
  /* #51: (@1[7] = @9) */
  for (rr=w1+7, ss=(&w9); rr!=w1+8; rr+=1) *rr = *ss++;
  /* #52: @9 = (@2*@10) */
  w9  = (w2*w10);
  /* #53: @11 = (@5*@8) */
  w11  = (w5*w8);
  /* #54: @9 = (@9-@11) */
  w9 -= w11;
  /* #55: @9 = (2.*@9) */
  w9 = (2.* w9 );
  /* #56: (@1[2] = @9) */
  for (rr=w1+2, ss=(&w9); rr!=w1+3; rr+=1) *rr = *ss++;
  /* #57: @10 = (@8*@10) */
  w10  = (w8*w10);
  /* #58: @5 = (@5*@2) */
  w5 *= w2;
  /* #59: @10 = (@10+@5) */
  w10 += w5;
  /* #60: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #61: (@1[5] = @10) */
  for (rr=w1+5, ss=(&w10); rr!=w1+6; rr+=1) *rr = *ss++;
  /* #62: @10 = 1 */
  w10 = 1.;
  /* #63: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #64: @8 = sq(@8) */
  w8 = casadi_sq( w8 );
  /* #65: @2 = (@2+@8) */
  w2 += w8;
  /* #66: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #67: @10 = (@10-@2) */
  w10 -= w2;
  /* #68: (@1[8] = @10) */
  for (rr=w1+8, ss=(&w10); rr!=w1+9; rr+=1) *rr = *ss++;
  /* #69: @10 = input[0][6] */
  w10 = arg[0] ? arg[0][6] : 0;
  /* #70: @2 = input[0][7] */
  w2 = arg[0] ? arg[0][7] : 0;
  /* #71: @8 = 0 */
  w8 = 0.;
  /* #72: @13 = vertcat(@10, @2, @8) */
  rr=w13;
  *rr++ = w10;
  *rr++ = w2;
  *rr++ = w8;
  /* #73: @0 = mac(@1,@13,@0) */
  for (i=0, rr=w0; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w1+j, tt=w13+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #74: @8 = @0[0] */
  for (rr=(&w8), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #75: output[0][0] = @8 */
  if (res[0]) res[0][0] = w8;
  /* #76: @8 = @0[1] */
  for (rr=(&w8), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #77: output[0][1] = @8 */
  if (res[0]) res[0][1] = w8;
  /* #78: @8 = 0.5 */
  w8 = 5.0000000000000000e-01;
  /* #79: @14 = zeros(4x1) */
  casadi_clear(w14, 4);
  /* #80: @5 = 0 */
  w5 = 0.;
  /* #81: @9 = 0 */
  w9 = 0.;
  /* #82: @11 = 0 */
  w11 = 0.;
  /* #83: @12 = input[0][8] */
  w12 = arg[0] ? arg[0][8] : 0;
  /* #84: @15 = (-@12) */
  w15 = (- w12 );
  /* #85: @16 = horzcat(@5, @9, @11, @15) */
  rr=w16;
  *rr++ = w5;
  *rr++ = w9;
  *rr++ = w11;
  *rr++ = w15;
  /* #86: @16 = @16' */
  /* #87: @5 = 0 */
  w5 = 0.;
  /* #88: @9 = 0 */
  w9 = 0.;
  /* #89: @11 = 0 */
  w11 = 0.;
  /* #90: @17 = horzcat(@5, @9, @12, @11) */
  rr=w17;
  *rr++ = w5;
  *rr++ = w9;
  *rr++ = w12;
  *rr++ = w11;
  /* #91: @17 = @17' */
  /* #92: @5 = 0 */
  w5 = 0.;
  /* #93: @9 = (-@12) */
  w9 = (- w12 );
  /* #94: @11 = 0 */
  w11 = 0.;
  /* #95: @15 = 0 */
  w15 = 0.;
  /* #96: @18 = horzcat(@5, @9, @11, @15) */
  rr=w18;
  *rr++ = w5;
  *rr++ = w9;
  *rr++ = w11;
  *rr++ = w15;
  /* #97: @18 = @18' */
  /* #98: @5 = 0 */
  w5 = 0.;
  /* #99: @9 = 0 */
  w9 = 0.;
  /* #100: @11 = 0 */
  w11 = 0.;
  /* #101: @19 = horzcat(@12, @5, @9, @11) */
  rr=w19;
  *rr++ = w12;
  *rr++ = w5;
  *rr++ = w9;
  *rr++ = w11;
  /* #102: @19 = @19' */
  /* #103: @20 = horzcat(@16, @17, @18, @19) */
  rr=w20;
  for (i=0, cs=w16; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<4; ++i) *rr++ = *cs++;
  /* #104: @21 = @20' */
  for (i=0, rr=w21, cs=w20; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #105: @16 = vertcat(@4, @6, @3, @7) */
  rr=w16;
  *rr++ = w4;
  *rr++ = w6;
  *rr++ = w3;
  *rr++ = w7;
  /* #106: @14 = mac(@21,@16,@14) */
  for (i=0, rr=w14; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w21+j, tt=w16+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #107: @14 = (@8*@14) */
  for (i=0, rr=w14, cs=w14; i<4; ++i) (*rr++)  = (w8*(*cs++));
  /* #108: output[0][2] = @14 */
  if (res[0]) casadi_copy(w14, 4, res[0]+2);
  /* #109: @8 = 0.0952381 */
  w8 = 9.5238095238095233e-02;
  /* #110: @4 = input[1][0] */
  w4 = arg[1] ? arg[1][0] : 0;
  /* #111: @6 = 0.3 */
  w6 = 2.9999999999999999e-01;
  /* #112: @6 = (@6*@10) */
  w6 *= w10;
  /* #113: @4 = (@4-@6) */
  w4 -= w6;
  /* #114: @6 = 10 */
  w6 = 10.;
  /* #115: @6 = (@6*@2) */
  w6 *= w2;
  /* #116: @6 = (@6*@12) */
  w6 *= w12;
  /* #117: @4 = (@4+@6) */
  w4 += w6;
  /* #118: @8 = (@8*@4) */
  w8 *= w4;
  /* #119: output[0][3] = @8 */
  if (res[0]) res[0][6] = w8;
  /* #120: @8 = 0.0769231 */
  w8 = 7.6923076923076927e-02;
  /* #121: @4 = -1.5 */
  w4 = -1.5000000000000000e+00;
  /* #122: @4 = (@4*@2) */
  w4 *= w2;
  /* #123: @2 = 10 */
  w2 = 10.;
  /* #124: @2 = (@2*@10) */
  w2 *= w10;
  /* #125: @2 = (@2*@12) */
  w2 *= w12;
  /* #126: @4 = (@4-@2) */
  w4 -= w2;
  /* #127: @8 = (@8*@4) */
  w8 *= w4;
  /* #128: output[0][4] = @8 */
  if (res[0]) res[0][7] = w8;
  /* #129: @8 = 0.379747 */
  w8 = 3.7974683544303789e-01;
  /* #130: @4 = input[1][1] */
  w4 = arg[1] ? arg[1][1] : 0;
  /* #131: @2 = 0.2 */
  w2 = 2.0000000000000001e-01;
  /* #132: @2 = (@2*@12) */
  w2 *= w12;
  /* #133: @4 = (@4-@2) */
  w4 -= w2;
  /* #134: @8 = (@8*@4) */
  w8 *= w4;
  /* #135: output[0][5] = @8 */
  if (res[0]) res[0][8] = w8;
  return 0;
}

CASADI_SYMBOL_EXPORT int USV_quat_ode_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int USV_quat_ode_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int USV_quat_ode_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void USV_quat_ode_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int USV_quat_ode_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void USV_quat_ode_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void USV_quat_ode_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void USV_quat_ode_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int USV_quat_ode_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int USV_quat_ode_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real USV_quat_ode_expl_ode_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* USV_quat_ode_expl_ode_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* USV_quat_ode_expl_ode_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* USV_quat_ode_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* USV_quat_ode_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int USV_quat_ode_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 83;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
