/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) USV_quat_ode_cost_ext_cost_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_c4 CASADI_PREFIX(c4)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[4] = {0, 0, 0, 0};
static const casadi_int casadi_s1[13] = {9, 1, 0, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8};
static const casadi_int casadi_s2[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s3[4] = {0, 1, 0, 0};
static const casadi_int casadi_s4[20] = {16, 1, 0, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};
static const casadi_int casadi_s5[5] = {1, 1, 0, 1, 0};

static const casadi_real casadi_c0[9] = {1.0000000000000001e-01, 0., 0., 0., 1.0000000000000001e-01, 0., 0., 0., 2.};
static const casadi_real casadi_c1[4] = {1., 0., 0., 1.};
static const casadi_real casadi_c2[4] = {6., 0., 0., 6.};
static const casadi_real casadi_c3[4] = {5., 0., 0., 5.};
static const casadi_real casadi_c4[4] = {5.0000000000000001e-03, 0., 0., 5.0000000000000001e-03};

/* USV_quat_ode_cost_ext_cost_fun:(i0[9],i1[2],i2[0],i3[16])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_int *cii;
  const casadi_real *cs;
  casadi_real w0, *w1=w+4, w2, w3, w4, w5, w6, w7, w8, *w9=w+14, *w10=w+18, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, *w21=w+32, *w22=w+35, *w23=w+38, *w24=w+47, *w25=w+49, w26, w27, w28, w29, w30, *w31=w+56, *w32=w+72, *w33=w+74, *w34=w+76;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #2: @2 = input[0][2] */
  w2 = arg[0] ? arg[0][2] : 0;
  /* #3: @3 = input[0][3] */
  w3 = arg[0] ? arg[0][3] : 0;
  /* #4: @4 = (-@3) */
  w4 = (- w3 );
  /* #5: @5 = input[0][4] */
  w5 = arg[0] ? arg[0][4] : 0;
  /* #6: @6 = (-@5) */
  w6 = (- w5 );
  /* #7: @7 = input[0][5] */
  w7 = arg[0] ? arg[0][5] : 0;
  /* #8: @8 = (-@7) */
  w8 = (- w7 );
  /* #9: @9 = vertcat(@2, @4, @6, @8) */
  rr=w9;
  *rr++ = w2;
  *rr++ = w4;
  *rr++ = w6;
  *rr++ = w8;
  /* #10: @10 = vertcat(@2, @3, @5, @7) */
  rr=w10;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w5;
  *rr++ = w7;
  /* #11: @4 = ||@10||_F */
  w4 = sqrt(casadi_dot(4, w10, w10));
  /* #12: @9 = (@9/@4) */
  for (i=0, rr=w9; i<4; ++i) (*rr++) /= w4;
  /* #13: @4 = @9[0] */
  for (rr=(&w4), ss=w9+0; ss!=w9+1; ss+=1) *rr++ = *ss;
  /* #14: @6 = input[3][11] */
  w6 = arg[3] ? arg[3][11] : 0;
  /* #15: @8 = (@4*@6) */
  w8  = (w4*w6);
  /* #16: @11 = @9[1] */
  for (rr=(&w11), ss=w9+1; ss!=w9+2; ss+=1) *rr++ = *ss;
  /* #17: @12 = input[3][12] */
  w12 = arg[3] ? arg[3][12] : 0;
  /* #18: @13 = (@11*@12) */
  w13  = (w11*w12);
  /* #19: @8 = (@8-@13) */
  w8 -= w13;
  /* #20: @13 = @9[2] */
  for (rr=(&w13), ss=w9+2; ss!=w9+3; ss+=1) *rr++ = *ss;
  /* #21: @14 = input[3][13] */
  w14 = arg[3] ? arg[3][13] : 0;
  /* #22: @15 = (@13*@14) */
  w15  = (w13*w14);
  /* #23: @8 = (@8-@15) */
  w8 -= w15;
  /* #24: @15 = @9[3] */
  for (rr=(&w15), ss=w9+3; ss!=w9+4; ss+=1) *rr++ = *ss;
  /* #25: @16 = input[3][14] */
  w16 = arg[3] ? arg[3][14] : 0;
  /* #26: @17 = (@15*@16) */
  w17  = (w15*w16);
  /* #27: @8 = (@8-@17) */
  w8 -= w17;
  /* #28: @17 = 0 */
  w17 = 0.;
  /* #29: @17 = (@8<@17) */
  w17  = (w8<w17);
  /* #30: @18 = (@4*@12) */
  w18  = (w4*w12);
  /* #31: @19 = (@11*@6) */
  w19  = (w11*w6);
  /* #32: @18 = (@18+@19) */
  w18 += w19;
  /* #33: @19 = (@13*@16) */
  w19  = (w13*w16);
  /* #34: @18 = (@18+@19) */
  w18 += w19;
  /* #35: @19 = (@15*@14) */
  w19  = (w15*w14);
  /* #36: @18 = (@18-@19) */
  w18 -= w19;
  /* #37: @19 = (@4*@14) */
  w19  = (w4*w14);
  /* #38: @20 = (@11*@16) */
  w20  = (w11*w16);
  /* #39: @19 = (@19-@20) */
  w19 -= w20;
  /* #40: @20 = (@13*@6) */
  w20  = (w13*w6);
  /* #41: @19 = (@19+@20) */
  w19 += w20;
  /* #42: @20 = (@15*@12) */
  w20  = (w15*w12);
  /* #43: @19 = (@19+@20) */
  w19 += w20;
  /* #44: @4 = (@4*@16) */
  w4 *= w16;
  /* #45: @11 = (@11*@14) */
  w11 *= w14;
  /* #46: @4 = (@4+@11) */
  w4 += w11;
  /* #47: @13 = (@13*@12) */
  w13 *= w12;
  /* #48: @4 = (@4-@13) */
  w4 -= w13;
  /* #49: @15 = (@15*@6) */
  w15 *= w6;
  /* #50: @4 = (@4+@15) */
  w4 += w15;
  /* #51: @9 = vertcat(@8, @18, @19, @4) */
  rr=w9;
  *rr++ = w8;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w4;
  /* #52: @10 = (-@9) */
  for (i=0, rr=w10, cs=w9; i<4; ++i) *rr++ = (- *cs++ );
  /* #53: @10 = (@17?@10:0) */
  for (i=0, rr=w10, cs=w10; i<4; ++i) (*rr++)  = (w17?(*cs++):0);
  /* #54: @17 = (!@17) */
  w17 = (! w17 );
  /* #55: @9 = (@17?@9:0) */
  for (i=0, rr=w9, cs=w9; i<4; ++i) (*rr++)  = (w17?(*cs++):0);
  /* #56: @10 = (@10+@9) */
  for (i=0, rr=w10, cs=w9; i<4; ++i) (*rr++) += (*cs++);
  /* #57: @21 = @10[1:4] */
  for (rr=w21, ss=w10+1; ss!=w10+4; ss+=1) *rr++ = *ss;
  /* #58: @22 = (2.*@21) */
  for (i=0, rr=w22, cs=w21; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #59: @17 = ||@21||_F */
  w17 = sqrt(casadi_dot(3, w21, w21));
  /* #60: @8 = @10[0] */
  for (rr=(&w8), ss=w10+0; ss!=w10+1; ss+=1) *rr++ = *ss;
  /* #61: @8 = atan2(@17,@8) */
  w8  = atan2(w17,w8);
  /* #62: @22 = (@22*@8) */
  for (i=0, rr=w22; i<3; ++i) (*rr++) *= w8;
  /* #63: @22 = (@22/@17) */
  for (i=0, rr=w22; i<3; ++i) (*rr++) /= w17;
  /* #64: @21 = @22' */
  casadi_copy(w22, 3, w21);
  /* #65: @23 = 
  [[0.1, 0, 0], 
   [0, 0.1, 0], 
   [0, 0, 2]] */
  casadi_copy(casadi_c0, 9, w23);
  /* #66: @1 = mac(@21,@23,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w21+j, tt=w23+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #67: @0 = mac(@1,@22,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w22+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #68: @17 = 0 */
  w17 = 0.;
  /* #69: @24 = zeros(1x2) */
  casadi_clear(w24, 2);
  /* #70: @25 = zeros(2x1) */
  casadi_clear(w25, 2);
  /* #71: @10 = 
  [[1, 0], 
   [0, 1]] */
  casadi_copy(casadi_c1, 4, w10);
  /* #72: @8 = 0 */
  w8 = 0.;
  /* #73: @18 = input[3][0] */
  w18 = arg[3] ? arg[3][0] : 0;
  /* #74: @19 = input[3][1] */
  w19 = arg[3] ? arg[3][1] : 0;
  /* #75: @4 = input[3][2] */
  w4 = arg[3] ? arg[3][2] : 0;
  /* #76: @15 = input[3][3] */
  w15 = arg[3] ? arg[3][3] : 0;
  /* #77: @13 = input[3][4] */
  w13 = arg[3] ? arg[3][4] : 0;
  /* #78: @11 = input[3][5] */
  w11 = arg[3] ? arg[3][5] : 0;
  /* #79: @20 = input[3][6] */
  w20 = arg[3] ? arg[3][6] : 0;
  /* #80: @26 = input[3][7] */
  w26 = arg[3] ? arg[3][7] : 0;
  /* #81: @27 = input[3][8] */
  w27 = arg[3] ? arg[3][8] : 0;
  /* #82: @28 = input[3][9] */
  w28 = arg[3] ? arg[3][9] : 0;
  /* #83: @29 = input[3][10] */
  w29 = arg[3] ? arg[3][10] : 0;
  /* #84: @30 = input[3][15] */
  w30 = arg[3] ? arg[3][15] : 0;
  /* #85: @31 = vertcat(@18, @19, @4, @15, @13, @11, @20, @26, @27, @28, @29, @6, @12, @14, @16, @30) */
  rr=w31;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w4;
  *rr++ = w15;
  *rr++ = w13;
  *rr++ = w11;
  *rr++ = w20;
  *rr++ = w26;
  *rr++ = w27;
  *rr++ = w28;
  *rr++ = w29;
  *rr++ = w6;
  *rr++ = w12;
  *rr++ = w14;
  *rr++ = w16;
  *rr++ = w30;
  /* #86: @32 = @31[3:5] */
  for (rr=w32, ss=w31+3; ss!=w31+5; ss+=1) *rr++ = *ss;
  /* #87: @18 = ||@32||_F */
  w18 = sqrt(casadi_dot(2, w32, w32));
  /* #88: @32 = (@32/@18) */
  for (i=0, rr=w32; i<2; ++i) (*rr++) /= w18;
  /* #89: @33 = @32' */
  casadi_copy(w32, 2, w33);
  /* #90: @8 = mac(@33,@32,@8) */
  for (i=0, rr=(&w8); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w33+j, tt=w32+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #91: @9 = @8[0, 0, 0, 0] */
  for (cii=casadi_s0, rr=w9, ss=(&w8); cii!=casadi_s0+4; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #92: @10 = (@10-@9) */
  for (i=0, rr=w10, cs=w9; i<4; ++i) (*rr++) -= (*cs++);
  /* #93: @33 = @31[:2] */
  for (rr=w33, ss=w31+0; ss!=w31+2; ss+=1) *rr++ = *ss;
  /* #94: @8 = input[0][0] */
  w8 = arg[0] ? arg[0][0] : 0;
  /* #95: @18 = input[0][1] */
  w18 = arg[0] ? arg[0][1] : 0;
  /* #96: @19 = input[0][6] */
  w19 = arg[0] ? arg[0][6] : 0;
  /* #97: @4 = input[0][7] */
  w4 = arg[0] ? arg[0][7] : 0;
  /* #98: @15 = input[0][8] */
  w15 = arg[0] ? arg[0][8] : 0;
  /* #99: @23 = vertcat(@8, @18, @2, @3, @5, @7, @19, @4, @15) */
  rr=w23;
  *rr++ = w8;
  *rr++ = w18;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w5;
  *rr++ = w7;
  *rr++ = w19;
  *rr++ = w4;
  *rr++ = w15;
  /* #100: @34 = @23[:2] */
  for (rr=w34, ss=w23+0; ss!=w23+2; ss+=1) *rr++ = *ss;
  /* #101: @33 = (@33-@34) */
  for (i=0, rr=w33, cs=w34; i<2; ++i) (*rr++) -= (*cs++);
  /* #102: @25 = mac(@10,@33,@25) */
  for (i=0, rr=w25; i<1; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w10+j, tt=w33+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #103: @34 = @25' */
  casadi_copy(w25, 2, w34);
  /* #104: @10 = 
  [[6, 0], 
   [0, 6]] */
  casadi_copy(casadi_c2, 4, w10);
  /* #105: @24 = mac(@34,@10,@24) */
  for (i=0, rr=w24; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w34+j, tt=w10+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #106: @17 = mac(@24,@25,@17) */
  for (i=0, rr=(&w17); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w24+j, tt=w25+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #107: @8 = 0 */
  w8 = 0.;
  /* #108: @24 = zeros(1x2) */
  casadi_clear(w24, 2);
  /* #109: @18 = dot(@32, @33) */
  w18 = casadi_dot(2, w32, w33);
  /* #110: @33 = (@18*@32) */
  for (i=0, rr=w33, cs=w32; i<2; ++i) (*rr++)  = (w18*(*cs++));
  /* #111: @25 = @33' */
  casadi_copy(w33, 2, w25);
  /* #112: @10 = 
  [[5, 0], 
   [0, 5]] */
  casadi_copy(casadi_c3, 4, w10);
  /* #113: @24 = mac(@25,@10,@24) */
  for (i=0, rr=w24; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w25+j, tt=w10+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #114: @8 = mac(@24,@33,@8) */
  for (i=0, rr=(&w8); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w24+j, tt=w33+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #115: @17 = (@17+@8) */
  w17 += w8;
  /* #116: @0 = (@0+@17) */
  w0 += w17;
  /* #117: @17 = 0.001 */
  w17 = 1.0000000000000000e-03;
  /* #118: @1 = zeros(3x1) */
  casadi_clear(w1, 3);
  /* #119: @23 = zeros(3x3) */
  casadi_clear(w23, 9);
  /* #120: @8 = 1 */
  w8 = 1.;
  /* #121: @18 = sq(@2) */
  w18 = casadi_sq( w2 );
  /* #122: @15 = sq(@3) */
  w15 = casadi_sq( w3 );
  /* #123: @18 = (@18+@15) */
  w18 += w15;
  /* #124: @15 = sq(@5) */
  w15 = casadi_sq( w5 );
  /* #125: @18 = (@18+@15) */
  w18 += w15;
  /* #126: @15 = sq(@7) */
  w15 = casadi_sq( w7 );
  /* #127: @18 = (@18+@15) */
  w18 += w15;
  /* #128: @18 = sqrt(@18) */
  w18 = sqrt( w18 );
  /* #129: @5 = (@5/@18) */
  w5 /= w18;
  /* #130: @15 = sq(@5) */
  w15 = casadi_sq( w5 );
  /* #131: @7 = (@7/@18) */
  w7 /= w18;
  /* #132: @13 = sq(@7) */
  w13 = casadi_sq( w7 );
  /* #133: @15 = (@15+@13) */
  w15 += w13;
  /* #134: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #135: @8 = (@8-@15) */
  w8 -= w15;
  /* #136: (@23[0] = @8) */
  for (rr=w23+0, ss=(&w8); rr!=w23+1; rr+=1) *rr = *ss++;
  /* #137: @3 = (@3/@18) */
  w3 /= w18;
  /* #138: @8 = (@3*@5) */
  w8  = (w3*w5);
  /* #139: @2 = (@2/@18) */
  w2 /= w18;
  /* #140: @18 = (@2*@7) */
  w18  = (w2*w7);
  /* #141: @8 = (@8-@18) */
  w8 -= w18;
  /* #142: @8 = (2.*@8) */
  w8 = (2.* w8 );
  /* #143: (@23[3] = @8) */
  for (rr=w23+3, ss=(&w8); rr!=w23+4; rr+=1) *rr = *ss++;
  /* #144: @8 = (@3*@7) */
  w8  = (w3*w7);
  /* #145: @18 = (@2*@5) */
  w18  = (w2*w5);
  /* #146: @8 = (@8+@18) */
  w8 += w18;
  /* #147: @8 = (2.*@8) */
  w8 = (2.* w8 );
  /* #148: (@23[6] = @8) */
  for (rr=w23+6, ss=(&w8); rr!=w23+7; rr+=1) *rr = *ss++;
  /* #149: @8 = (@3*@5) */
  w8  = (w3*w5);
  /* #150: @18 = (@2*@7) */
  w18  = (w2*w7);
  /* #151: @8 = (@8+@18) */
  w8 += w18;
  /* #152: @8 = (2.*@8) */
  w8 = (2.* w8 );
  /* #153: (@23[1] = @8) */
  for (rr=w23+1, ss=(&w8); rr!=w23+2; rr+=1) *rr = *ss++;
  /* #154: @8 = 1 */
  w8 = 1.;
  /* #155: @18 = sq(@3) */
  w18 = casadi_sq( w3 );
  /* #156: @15 = sq(@7) */
  w15 = casadi_sq( w7 );
  /* #157: @18 = (@18+@15) */
  w18 += w15;
  /* #158: @18 = (2.*@18) */
  w18 = (2.* w18 );
  /* #159: @8 = (@8-@18) */
  w8 -= w18;
  /* #160: (@23[4] = @8) */
  for (rr=w23+4, ss=(&w8); rr!=w23+5; rr+=1) *rr = *ss++;
  /* #161: @8 = (@5*@7) */
  w8  = (w5*w7);
  /* #162: @18 = (@2*@3) */
  w18  = (w2*w3);
  /* #163: @8 = (@8-@18) */
  w8 -= w18;
  /* #164: @8 = (2.*@8) */
  w8 = (2.* w8 );
  /* #165: (@23[7] = @8) */
  for (rr=w23+7, ss=(&w8); rr!=w23+8; rr+=1) *rr = *ss++;
  /* #166: @8 = (@3*@7) */
  w8  = (w3*w7);
  /* #167: @18 = (@2*@5) */
  w18  = (w2*w5);
  /* #168: @8 = (@8-@18) */
  w8 -= w18;
  /* #169: @8 = (2.*@8) */
  w8 = (2.* w8 );
  /* #170: (@23[2] = @8) */
  for (rr=w23+2, ss=(&w8); rr!=w23+3; rr+=1) *rr = *ss++;
  /* #171: @7 = (@5*@7) */
  w7  = (w5*w7);
  /* #172: @2 = (@2*@3) */
  w2 *= w3;
  /* #173: @7 = (@7+@2) */
  w7 += w2;
  /* #174: @7 = (2.*@7) */
  w7 = (2.* w7 );
  /* #175: (@23[5] = @7) */
  for (rr=w23+5, ss=(&w7); rr!=w23+6; rr+=1) *rr = *ss++;
  /* #176: @7 = 1 */
  w7 = 1.;
  /* #177: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #178: @5 = sq(@5) */
  w5 = casadi_sq( w5 );
  /* #179: @3 = (@3+@5) */
  w3 += w5;
  /* #180: @3 = (2.*@3) */
  w3 = (2.* w3 );
  /* #181: @7 = (@7-@3) */
  w7 -= w3;
  /* #182: (@23[8] = @7) */
  for (rr=w23+8, ss=(&w7); rr!=w23+9; rr+=1) *rr = *ss++;
  /* #183: @7 = 0 */
  w7 = 0.;
  /* #184: @22 = vertcat(@19, @4, @7) */
  rr=w22;
  *rr++ = w19;
  *rr++ = w4;
  *rr++ = w7;
  /* #185: @1 = mac(@23,@22,@1) */
  for (i=0, rr=w1; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w23+j, tt=w22+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #186: @24 = @1[:2] */
  for (rr=w24, ss=w1+0; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #187: @19 = dot(@32, @24) */
  w19 = casadi_dot(2, w32, w24);
  /* #188: @17 = (@17*@19) */
  w17 *= w19;
  /* #189: @0 = (@0-@17) */
  w0 -= w17;
  /* #190: @17 = 0 */
  w17 = 0.;
  /* #191: @32 = zeros(1x2) */
  casadi_clear(w32, 2);
  /* #192: @19 = input[1][0] */
  w19 = arg[1] ? arg[1][0] : 0;
  /* #193: @4 = input[1][1] */
  w4 = arg[1] ? arg[1][1] : 0;
  /* #194: @24 = vertcat(@19, @4) */
  rr=w24;
  *rr++ = w19;
  *rr++ = w4;
  /* #195: @33 = @24' */
  casadi_copy(w24, 2, w33);
  /* #196: @10 = 
  [[0.005, 0], 
   [0, 0.005]] */
  casadi_copy(casadi_c4, 4, w10);
  /* #197: @32 = mac(@33,@10,@32) */
  for (i=0, rr=w32; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w33+j, tt=w10+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #198: @17 = mac(@32,@24,@17) */
  for (i=0, rr=(&w17); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w32+j, tt=w24+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #199: @0 = (@0+@17) */
  w0 += w17;
  /* #200: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  return 0;
}

CASADI_SYMBOL_EXPORT int USV_quat_ode_cost_ext_cost_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int USV_quat_ode_cost_ext_cost_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int USV_quat_ode_cost_ext_cost_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void USV_quat_ode_cost_ext_cost_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int USV_quat_ode_cost_ext_cost_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void USV_quat_ode_cost_ext_cost_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void USV_quat_ode_cost_ext_cost_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void USV_quat_ode_cost_ext_cost_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int USV_quat_ode_cost_ext_cost_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int USV_quat_ode_cost_ext_cost_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real USV_quat_ode_cost_ext_cost_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* USV_quat_ode_cost_ext_cost_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* USV_quat_ode_cost_ext_cost_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* USV_quat_ode_cost_ext_cost_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    case 2: return casadi_s3;
    case 3: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* USV_quat_ode_cost_ext_cost_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int USV_quat_ode_cost_ext_cost_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 20;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 78;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
