/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) USV_ode_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[18] = {14, 1, 0, 14, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13};
static const casadi_int casadi_s3[11] = {9, 1, 0, 7, 2, 3, 4, 5, 6, 7, 8};

/* USV_ode_expl_vde_adj:(i0[6],i1[6],i2[3],i3[14])->(o0[9x1,7nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, *w3=w+3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13;
  /* #0: @0 = input[0][2] */
  w0 = arg[0] ? arg[0][2] : 0;
  /* #1: @1 = cos(@0) */
  w1 = cos( w0 );
  /* #2: @2 = input[0][3] */
  w2 = arg[0] ? arg[0][3] : 0;
  /* #3: @3 = input[1][0] */
  casadi_copy(arg[1], 6, w3);
  /* #4: {@4, @5, @6, @7, @8, @9} = vertsplit(@3) */
  w4 = w3[0];
  w5 = w3[1];
  w6 = w3[2];
  w7 = w3[3];
  w8 = w3[4];
  w9 = w3[5];
  /* #5: @10 = (@2*@5) */
  w10  = (w2*w5);
  /* #6: @1 = (@1*@10) */
  w1 *= w10;
  /* #7: @10 = sin(@0) */
  w10 = sin( w0 );
  /* #8: @11 = input[0][4] */
  w11 = arg[0] ? arg[0][4] : 0;
  /* #9: @12 = (@11*@5) */
  w12  = (w11*w5);
  /* #10: @10 = (@10*@12) */
  w10 *= w12;
  /* #11: @1 = (@1-@10) */
  w1 -= w10;
  /* #12: @10 = cos(@0) */
  w10 = cos( w0 );
  /* #13: @12 = (@11*@4) */
  w12  = (w11*w4);
  /* #14: @10 = (@10*@12) */
  w10 *= w12;
  /* #15: @1 = (@1-@10) */
  w1 -= w10;
  /* #16: @10 = sin(@0) */
  w10 = sin( w0 );
  /* #17: @12 = (@2*@4) */
  w12  = (w2*w4);
  /* #18: @10 = (@10*@12) */
  w10 *= w12;
  /* #19: @1 = (@1-@10) */
  w1 -= w10;
  /* #20: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  /* #21: @1 = 0.0181818 */
  w1 = 1.8181818181818181e-02;
  /* #22: @1 = (@1*@7) */
  w1 *= w7;
  /* #23: @7 = (-@1) */
  w7 = (- w1 );
  /* #24: @7 = (2.*@7) */
  w7 = (2.* w7 );
  /* #25: @10 = 50 */
  w10 = 50.;
  /* #26: @12 = input[0][5] */
  w12 = arg[0] ? arg[0][5] : 0;
  /* #27: @13 = 0.0142857 */
  w13 = 1.4285714285714285e-02;
  /* #28: @13 = (@13*@8) */
  w13 *= w8;
  /* #29: @8 = (@12*@13) */
  w8  = (w12*w13);
  /* #30: @8 = (@10*@8) */
  w8  = (w10*w8);
  /* #31: @7 = (@7-@8) */
  w7 -= w8;
  /* #32: @8 = sin(@0) */
  w8 = sin( w0 );
  /* #33: @8 = (@8*@5) */
  w8 *= w5;
  /* #34: @7 = (@7+@8) */
  w7 += w8;
  /* #35: @8 = cos(@0) */
  w8 = cos( w0 );
  /* #36: @8 = (@8*@4) */
  w8 *= w4;
  /* #37: @7 = (@7+@8) */
  w7 += w8;
  /* #38: output[0][1] = @7 */
  if (res[0]) res[0][1] = w7;
  /* #39: @7 = 50 */
  w7 = 50.;
  /* #40: @12 = (@12*@1) */
  w12 *= w1;
  /* #41: @12 = (@7*@12) */
  w12  = (w7*w12);
  /* #42: @8 = 5 */
  w8 = 5.;
  /* #43: @8 = (@8*@13) */
  w8 *= w13;
  /* #44: @12 = (@12-@8) */
  w12 -= w8;
  /* #45: @8 = cos(@0) */
  w8 = cos( w0 );
  /* #46: @8 = (@8*@5) */
  w8 *= w5;
  /* #47: @12 = (@12+@8) */
  w12 += w8;
  /* #48: @0 = sin(@0) */
  w0 = sin( w0 );
  /* #49: @0 = (@0*@4) */
  w0 *= w4;
  /* #50: @12 = (@12-@0) */
  w12 -= w0;
  /* #51: output[0][2] = @12 */
  if (res[0]) res[0][2] = w12;
  /* #52: @10 = (@10*@2) */
  w10 *= w2;
  /* #53: @10 = (@10*@13) */
  w10 *= w13;
  /* #54: @10 = (-@10) */
  w10 = (- w10 );
  /* #55: @2 = 0.0666667 */
  w2 = 6.6666666666666666e-02;
  /* #56: @2 = (@2*@9) */
  w2 *= w9;
  /* #57: @10 = (@10-@2) */
  w10 -= w2;
  /* #58: @7 = (@7*@11) */
  w7 *= w11;
  /* #59: @7 = (@7*@1) */
  w7 *= w1;
  /* #60: @10 = (@10+@7) */
  w10 += w7;
  /* #61: @10 = (@10+@6) */
  w10 += w6;
  /* #62: output[0][3] = @10 */
  if (res[0]) res[0][3] = w10;
  /* #63: output[0][4] = @1 */
  if (res[0]) res[0][4] = w1;
  /* #64: output[0][5] = @13 */
  if (res[0]) res[0][5] = w13;
  /* #65: output[0][6] = @2 */
  if (res[0]) res[0][6] = w2;
  return 0;
}

CASADI_SYMBOL_EXPORT int USV_ode_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int USV_ode_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int USV_ode_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void USV_ode_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int USV_ode_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void USV_ode_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void USV_ode_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void USV_ode_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int USV_ode_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int USV_ode_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real USV_ode_expl_vde_adj_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* USV_ode_expl_vde_adj_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* USV_ode_expl_vde_adj_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* USV_ode_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* USV_ode_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int USV_ode_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 7;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 19;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
