/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) USV_ode_cost_ext_cost_0_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s22 CASADI_PREFIX(s22)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sparsify CASADI_PREFIX(sparsify)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_sparsify(const casadi_real* x, casadi_real* y, const casadi_int* sp_y, casadi_int tr) {
  casadi_int nrow_y, ncol_y, i, el;
  const casadi_int *colind_y, *row_y;
  nrow_y = sp_y[0];
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y+ncol_y+3;
  if (tr) {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[i + row_y[el]*ncol_y]);
      }
    }
  } else {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[row_y[el]]);
      }
      x += nrow_y;
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[4] = {0, 0, 0, 0};
static const casadi_int casadi_s1[9] = {1, 3, 0, 1, 2, 3, 0, 0, 0};
static const casadi_int casadi_s2[15] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s3[7] = {1, 3, 0, 1, 1, 1, 0};
static const casadi_int casadi_s4[5] = {2, 1, 0, 1, 0};
static const casadi_int casadi_s5[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s6[9] = {2, 2, 0, 2, 4, 0, 1, 0, 1};
static const casadi_int casadi_s7[8] = {0, 1, 2, 9, 10, 13, 14, 15};
static const casadi_int casadi_s8[8] = {0, 3, 6, 9, 11, 13, 16, 17};
static const casadi_int casadi_s9[7] = {1, 3, 0, 0, 1, 1, 0};
static const casadi_int casadi_s10[5] = {2, 1, 0, 1, 1};
static const casadi_int casadi_s11[5] = {3, 4, 5, 11, 12};
static const casadi_int casadi_s12[5] = {1, 4, 7, 10, 12};
static const casadi_int casadi_s13[7] = {1, 3, 0, 0, 0, 1, 0};
static const casadi_int casadi_s14[30] = {9, 9, 0, 3, 6, 9, 11, 13, 16, 17, 18, 18, 0, 1, 2, 0, 1, 2, 0, 1, 2, 3, 4, 3, 4, 5, 6, 7, 5, 5};
static const casadi_int casadi_s15[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s16[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s17[4] = {0, 1, 0, 0};
static const casadi_int casadi_s18[18] = {14, 1, 0, 14, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13};
static const casadi_int casadi_s19[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s20[13] = {9, 1, 0, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8};
static const casadi_int casadi_s21[3] = {0, 0, 0};
static const casadi_int casadi_s22[12] = {0, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};

static const casadi_real casadi_c0[4] = {1., 0., 0., 1.};
static const casadi_real casadi_c1[4] = {5., 0., 0., 5.};
static const casadi_real casadi_c2[9] = {1.0000000000000000e-04, 0., 0., 0., 1.0000000000000000e-04, 0., 0., 0., 1.0000000000000000e-04};

/* USV_ode_cost_ext_cost_0_fun_jac_hess:(i0[6],i1[3],i2[0],i3[14])->(o0,o1[9],o2[9x9,18nz],o3[],o4[0x9]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_int *cii;
  const casadi_real *cr, *cs;
  casadi_real w0, w1, w2, w3, w4, *w5=w+7, *w6=w+9, *w7=w+11, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, *w22=w+29, *w23=w+43, *w24=w+45, *w25=w+47, *w26=w+51, *w27=w+57, *w28=w+59, *w29=w+61, *w30=w+65, *w31=w+68, *w32=w+71, *w33=w+74, *w34=w+83, *w35=w+92, *w36=w+96, *w37=w+100, w38, w39, w40, *w41=w+107, *w42=w+125, *w45=w+129, *w46=w+138, *w47=w+146, *w52=w+151;
  /* #0: @0 = input[3][8] */
  w0 = arg[3] ? arg[3][8] : 0;
  /* #1: @1 = input[0][2] */
  w1 = arg[0] ? arg[0][2] : 0;
  /* #2: @2 = (@0-@1) */
  w2  = (w0-w1);
  /* #3: @3 = sq(@2) */
  w3 = casadi_sq( w2 );
  /* #4: @4 = 0 */
  w4 = 0.;
  /* #5: @5 = zeros(1x2) */
  casadi_clear(w5, 2);
  /* #6: @6 = zeros(2x1) */
  casadi_clear(w6, 2);
  /* #7: @7 = 
  [[1, 0], 
   [0, 1]] */
  casadi_copy(casadi_c0, 4, w7);
  /* #8: @8 = 0 */
  w8 = 0.;
  /* #9: @9 = input[3][0] */
  w9 = arg[3] ? arg[3][0] : 0;
  /* #10: @10 = input[3][1] */
  w10 = arg[3] ? arg[3][1] : 0;
  /* #11: @11 = input[3][2] */
  w11 = arg[3] ? arg[3][2] : 0;
  /* #12: @12 = input[3][3] */
  w12 = arg[3] ? arg[3][3] : 0;
  /* #13: @13 = input[3][4] */
  w13 = arg[3] ? arg[3][4] : 0;
  /* #14: @14 = input[3][5] */
  w14 = arg[3] ? arg[3][5] : 0;
  /* #15: @15 = input[3][6] */
  w15 = arg[3] ? arg[3][6] : 0;
  /* #16: @16 = input[3][7] */
  w16 = arg[3] ? arg[3][7] : 0;
  /* #17: @17 = input[3][9] */
  w17 = arg[3] ? arg[3][9] : 0;
  /* #18: @18 = input[3][10] */
  w18 = arg[3] ? arg[3][10] : 0;
  /* #19: @19 = input[3][11] */
  w19 = arg[3] ? arg[3][11] : 0;
  /* #20: @20 = input[3][12] */
  w20 = arg[3] ? arg[3][12] : 0;
  /* #21: @21 = input[3][13] */
  w21 = arg[3] ? arg[3][13] : 0;
  /* #22: @22 = vertcat(@9, @10, @11, @12, @13, @14, @15, @16, @0, @17, @18, @19, @20, @21) */
  rr=w22;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w0;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w20;
  *rr++ = w21;
  /* #23: @23 = @22[3:5] */
  for (rr=w23, ss=w22+3; ss!=w22+5; ss+=1) *rr++ = *ss;
  /* #24: @24 = @23' */
  casadi_copy(w23, 2, w24);
  /* #25: @8 = mac(@24,@23,@8) */
  for (i=0, rr=(&w8); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w24+j, tt=w23+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #26: @25 = @8[0, 0, 0, 0] */
  for (cii=casadi_s0, rr=w25, ss=(&w8); cii!=casadi_s0+4; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #27: @7 = (@7-@25) */
  for (i=0, rr=w7, cs=w25; i<4; ++i) (*rr++) -= (*cs++);
  /* #28: @24 = @22[:2] */
  for (rr=w24, ss=w22+0; ss!=w22+2; ss+=1) *rr++ = *ss;
  /* #29: @8 = input[0][0] */
  w8 = arg[0] ? arg[0][0] : 0;
  /* #30: @9 = input[0][1] */
  w9 = arg[0] ? arg[0][1] : 0;
  /* #31: @10 = input[0][3] */
  w10 = arg[0] ? arg[0][3] : 0;
  /* #32: @11 = input[0][4] */
  w11 = arg[0] ? arg[0][4] : 0;
  /* #33: @12 = input[0][5] */
  w12 = arg[0] ? arg[0][5] : 0;
  /* #34: @26 = vertcat(@8, @9, @1, @10, @11, @12) */
  rr=w26;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w1;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  /* #35: @27 = @26[:2] */
  for (rr=w27, ss=w26+0; ss!=w26+2; ss+=1) *rr++ = *ss;
  /* #36: @24 = (@24-@27) */
  for (i=0, rr=w24, cs=w27; i<2; ++i) (*rr++) -= (*cs++);
  /* #37: @6 = mac(@7,@24,@6) */
  for (i=0, rr=w6; i<1; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w7+j, tt=w24+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #38: @27 = @6' */
  casadi_copy(w6, 2, w27);
  /* #39: @25 = 
  [[5, 0], 
   [0, 5]] */
  casadi_copy(casadi_c1, 4, w25);
  /* #40: @5 = mac(@27,@25,@5) */
  for (i=0, rr=w5; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w27+j, tt=w25+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #41: @4 = mac(@5,@6,@4) */
  for (i=0, rr=(&w4); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w5+j, tt=w6+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #42: @8 = 0 */
  w8 = 0.;
  /* #43: @27 = zeros(1x2) */
  casadi_clear(w27, 2);
  /* #44: @9 = dot(@23, @24) */
  w9 = casadi_dot(2, w23, w24);
  /* #45: @24 = (@9*@23) */
  for (i=0, rr=w24, cs=w23; i<2; ++i) (*rr++)  = (w9*(*cs++));
  /* #46: @28 = @24' */
  casadi_copy(w24, 2, w28);
  /* #47: @29 = 
  [[5, 0], 
   [0, 5]] */
  casadi_copy(casadi_c1, 4, w29);
  /* #48: @27 = mac(@28,@29,@27) */
  for (i=0, rr=w27; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w28+j, tt=w29+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #49: @8 = mac(@27,@24,@8) */
  for (i=0, rr=(&w8); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w27+j, tt=w24+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #50: @4 = (@4+@8) */
  w4 += w8;
  /* #51: @3 = (@3+@4) */
  w3 += w4;
  /* #52: @4 = 0.01 */
  w4 = 1.0000000000000000e-02;
  /* #53: @8 = cos(@1) */
  w8 = cos( w1 );
  /* #54: @9 = (@10*@8) */
  w9  = (w10*w8);
  /* #55: @12 = sin(@1) */
  w12 = sin( w1 );
  /* #56: @13 = (@11*@12) */
  w13  = (w11*w12);
  /* #57: @9 = (@9-@13) */
  w9 -= w13;
  /* #58: @13 = sin(@1) */
  w13 = sin( w1 );
  /* #59: @14 = (@10*@13) */
  w14  = (w10*w13);
  /* #60: @15 = cos(@1) */
  w15 = cos( w1 );
  /* #61: @16 = (@11*@15) */
  w16  = (w11*w15);
  /* #62: @14 = (@14+@16) */
  w14 += w16;
  /* #63: @28 = vertcat(@9, @14) */
  rr=w28;
  *rr++ = w9;
  *rr++ = w14;
  /* #64: @9 = dot(@23, @28) */
  w9 = casadi_dot(2, w23, w28);
  /* #65: @4 = (@4*@9) */
  w4 *= w9;
  /* #66: @3 = (@3-@4) */
  w3 -= w4;
  /* #67: @4 = 0 */
  w4 = 0.;
  /* #68: @30 = zeros(1x3) */
  casadi_clear(w30, 3);
  /* #69: @9 = input[1][0] */
  w9 = arg[1] ? arg[1][0] : 0;
  /* #70: @14 = input[1][1] */
  w14 = arg[1] ? arg[1][1] : 0;
  /* #71: @16 = input[1][2] */
  w16 = arg[1] ? arg[1][2] : 0;
  /* #72: @31 = vertcat(@9, @14, @16) */
  rr=w31;
  *rr++ = w9;
  *rr++ = w14;
  *rr++ = w16;
  /* #73: @32 = @31' */
  casadi_copy(w31, 3, w32);
  /* #74: @33 = 
  [[0.0001, 0, 0], 
   [0, 0.0001, 0], 
   [0, 0, 0.0001]] */
  casadi_copy(casadi_c2, 9, w33);
  /* #75: @30 = mac(@32,@33,@30) */
  for (i=0, rr=w30; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w32+j, tt=w33+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #76: @4 = mac(@30,@31,@4) */
  for (i=0, rr=(&w4); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w30+j, tt=w31+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #77: @3 = (@3+@4) */
  w3 += w4;
  /* #78: output[0][0] = @3 */
  if (res[0]) res[0][0] = w3;
  /* #79: @30 = @30' */
  /* #80: @32 = zeros(1x3) */
  casadi_clear(w32, 3);
  /* #81: @31 = @31' */
  /* #82: @34 = @33' */
  for (i=0, rr=w34, cs=w33; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #83: @32 = mac(@31,@34,@32) */
  for (i=0, rr=w32; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w31+j, tt=w34+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #84: @32 = @32' */
  /* #85: @30 = (@30+@32) */
  for (i=0, rr=w30, cs=w32; i<3; ++i) (*rr++) += (*cs++);
  /* #86: {@3, @4, @9} = vertsplit(@30) */
  w3 = w30[0];
  w4 = w30[1];
  w9 = w30[2];
  /* #87: output[1][0] = @3 */
  if (res[1]) res[1][0] = w3;
  /* #88: output[1][1] = @4 */
  if (res[1]) res[1][1] = w4;
  /* #89: output[1][2] = @9 */
  if (res[1]) res[1][2] = w9;
  /* #90: @26 = zeros(6x1) */
  casadi_clear(w26, 6);
  /* #91: @27 = @27' */
  /* #92: @28 = zeros(1x2) */
  casadi_clear(w28, 2);
  /* #93: @24 = @24' */
  /* #94: @35 = @29' */
  for (i=0, rr=w35, cs=w29; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #95: @28 = mac(@24,@35,@28) */
  for (i=0, rr=w28; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w24+j, tt=w35+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #96: @28 = @28' */
  /* #97: @27 = (@27+@28) */
  for (i=0, rr=w27, cs=w28; i<2; ++i) (*rr++) += (*cs++);
  /* #98: @9 = dot(@23, @27) */
  w9 = casadi_dot(2, w23, w27);
  /* #99: @27 = (@9*@23) */
  for (i=0, rr=w27, cs=w23; i<2; ++i) (*rr++)  = (w9*(*cs++));
  /* #100: @28 = zeros(2x1) */
  casadi_clear(w28, 2);
  /* #101: @36 = @7' */
  for (i=0, rr=w36, cs=w7; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #102: @5 = @5' */
  /* #103: @24 = zeros(1x2) */
  casadi_clear(w24, 2);
  /* #104: @6 = @6' */
  /* #105: @37 = @25' */
  for (i=0, rr=w37, cs=w25; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #106: @24 = mac(@6,@37,@24) */
  for (i=0, rr=w24; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w6+j, tt=w37+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #107: @24 = @24' */
  /* #108: @5 = (@5+@24) */
  for (i=0, rr=w5, cs=w24; i<2; ++i) (*rr++) += (*cs++);
  /* #109: @28 = mac(@36,@5,@28) */
  for (i=0, rr=w28; i<1; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w36+j, tt=w5+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #110: @27 = (@27+@28) */
  for (i=0, rr=w27, cs=w28; i<2; ++i) (*rr++) += (*cs++);
  /* #111: @27 = (-@27) */
  for (i=0, rr=w27, cs=w27; i<2; ++i) *rr++ = (- *cs++ );
  /* #112: (@26[:2] += @27) */
  for (rr=w26+0, ss=w27; rr!=w26+2; rr+=1) *rr += *ss++;
  /* #113: {@9, @4, @3, @14, @16, @0} = vertsplit(@26) */
  w9 = w26[0];
  w4 = w26[1];
  w3 = w26[2];
  w14 = w26[3];
  w16 = w26[4];
  w0 = w26[5];
  /* #114: output[1][3] = @9 */
  if (res[1]) res[1][3] = w9;
  /* #115: output[1][4] = @4 */
  if (res[1]) res[1][4] = w4;
  /* #116: @4 = cos(@1) */
  w4 = cos( w1 );
  /* #117: @9 = -0.01 */
  w9 = -1.0000000000000000e-02;
  /* #118: @27 = (@9*@23) */
  for (i=0, rr=w27, cs=w23; i<2; ++i) (*rr++)  = (w9*(*cs++));
  /* #119: {@9, @17} = vertsplit(@27) */
  w9 = w27[0];
  w17 = w27[1];
  /* #120: @18 = (@10*@17) */
  w18  = (w10*w17);
  /* #121: @19 = (@4*@18) */
  w19  = (w4*w18);
  /* #122: @20 = sin(@1) */
  w20 = sin( w1 );
  /* #123: @21 = (@11*@17) */
  w21  = (w11*w17);
  /* #124: @38 = (@20*@21) */
  w38  = (w20*w21);
  /* #125: @19 = (@19-@38) */
  w19 -= w38;
  /* #126: @38 = cos(@1) */
  w38 = cos( w1 );
  /* #127: @11 = (@11*@9) */
  w11 *= w9;
  /* #128: @39 = (@38*@11) */
  w39  = (w38*w11);
  /* #129: @19 = (@19-@39) */
  w19 -= w39;
  /* #130: @39 = sin(@1) */
  w39 = sin( w1 );
  /* #131: @10 = (@10*@9) */
  w10 *= w9;
  /* #132: @40 = (@39*@10) */
  w40  = (w39*w10);
  /* #133: @19 = (@19-@40) */
  w19 -= w40;
  /* #134: @19 = (@19+@3) */
  w19 += w3;
  /* #135: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #136: @19 = (@19-@2) */
  w19 -= w2;
  /* #137: output[1][5] = @19 */
  if (res[1]) res[1][5] = w19;
  /* #138: @13 = (@13*@17) */
  w13 *= w17;
  /* #139: @8 = (@8*@9) */
  w8 *= w9;
  /* #140: @13 = (@13+@8) */
  w13 += w8;
  /* #141: @13 = (@13+@14) */
  w13 += w14;
  /* #142: output[1][6] = @13 */
  if (res[1]) res[1][6] = w13;
  /* #143: @15 = (@15*@17) */
  w15 *= w17;
  /* #144: @12 = (@12*@9) */
  w12 *= w9;
  /* #145: @15 = (@15-@12) */
  w15 -= w12;
  /* #146: @15 = (@15+@16) */
  w15 += w16;
  /* #147: output[1][7] = @15 */
  if (res[1]) res[1][7] = w15;
  /* #148: output[1][8] = @0 */
  if (res[1]) res[1][8] = w0;
  /* #149: @41 = zeros(9x9,18nz) */
  casadi_clear(w41, 18);
  /* #150: @30 = zeros(1x3) */
  casadi_clear(w30, 3);
  /* #151: @42 = ones(9x1,4nz) */
  casadi_fill(w42, 4, 1.);
  /* #152: {@0, NULL, NULL, @15, NULL, @16, NULL, NULL, NULL} = vertsplit(@42) */
  w0 = w42[0];
  w15 = w42[1];
  w16 = w42[2];
  /* #153: @43 = 00 */
  /* #154: @44 = 00 */
  /* #155: @12 = vertcat(@0, @43, @44) */
  rr=(&w12);
  *rr++ = w0;
  /* #156: @0 = @12' */
  casadi_copy((&w12), 1, (&w0));
  /* #157: @30 = mac(@0,@33,@30) */
  casadi_mtimes((&w0), casadi_s3, w33, casadi_s2, w30, casadi_s1, w, 0);
  /* #158: @30 = @30' */
  /* #159: @32 = zeros(1x3) */
  casadi_clear(w32, 3);
  /* #160: @12 = @12' */
  /* #161: @32 = mac(@12,@34,@32) */
  casadi_mtimes((&w12), casadi_s3, w34, casadi_s2, w32, casadi_s1, w, 0);
  /* #162: @32 = @32' */
  /* #163: @30 = (@30+@32) */
  for (i=0, rr=w30, cs=w32; i<3; ++i) (*rr++) += (*cs++);
  /* #164: {@12, @0, @13} = vertsplit(@30) */
  w12 = w30[0];
  w0 = w30[1];
  w13 = w30[2];
  /* #165: @26 = zeros(6x1) */
  casadi_clear(w26, 6);
  /* #166: @27 = zeros(1x2) */
  casadi_clear(w27, 2);
  /* #167: @14 = project(@23) */
  casadi_sparsify(w23, (&w14), casadi_s4, 0);
  /* #168: @8 = @15[0] */
  for (rr=(&w8), ss=(&w15)+0; ss!=(&w15)+1; ss+=1) *rr++ = *ss;
  /* #169: @8 = (-@8) */
  w8 = (- w8 );
  /* #170: @15 = dot(@14, @8) */
  w15 = casadi_dot(1, (&w14), (&w8));
  /* #171: @28 = (@23*@15) */
  for (i=0, rr=w28, cr=w23; i<2; ++i) (*rr++)  = ((*cr++)*w15);
  /* #172: @5 = @28' */
  casadi_copy(w28, 2, w5);
  /* #173: @27 = mac(@5,@29,@27) */
  for (i=0, rr=w27; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w5+j, tt=w29+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #174: @27 = @27' */
  /* #175: @5 = zeros(1x2) */
  casadi_clear(w5, 2);
  /* #176: @28 = @28' */
  /* #177: @5 = mac(@28,@35,@5) */
  for (i=0, rr=w5; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w28+j, tt=w35+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #178: @5 = @5' */
  /* #179: @27 = (@27+@5) */
  for (i=0, rr=w27, cs=w5; i<2; ++i) (*rr++) += (*cs++);
  /* #180: @15 = dot(@23, @27) */
  w15 = casadi_dot(2, w23, w27);
  /* #181: @27 = (@23*@15) */
  for (i=0, rr=w27, cr=w23; i<2; ++i) (*rr++)  = ((*cr++)*w15);
  /* #182: @5 = zeros(2x1) */
  casadi_clear(w5, 2);
  /* #183: @28 = zeros(1x2) */
  casadi_clear(w28, 2);
  /* #184: @24 = zeros(2x1) */
  casadi_clear(w24, 2);
  /* #185: @24 = mac(@7,@8,@24) */
  casadi_mtimes(w7, casadi_s6, (&w8), casadi_s4, w24, casadi_s5, w, 0);
  /* #186: @6 = @24' */
  casadi_copy(w24, 2, w6);
  /* #187: @28 = mac(@6,@25,@28) */
  for (i=0, rr=w28; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w6+j, tt=w25+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #188: @28 = @28' */
  /* #189: @6 = zeros(1x2) */
  casadi_clear(w6, 2);
  /* #190: @24 = @24' */
  /* #191: @6 = mac(@24,@37,@6) */
  for (i=0, rr=w6; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w24+j, tt=w37+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #192: @6 = @6' */
  /* #193: @28 = (@28+@6) */
  for (i=0, rr=w28, cs=w6; i<2; ++i) (*rr++) += (*cs++);
  /* #194: @5 = mac(@36,@28,@5) */
  for (i=0, rr=w5; i<1; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w36+j, tt=w28+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #195: @27 = (@27+@5) */
  for (i=0, rr=w27, cs=w5; i<2; ++i) (*rr++) += (*cs++);
  /* #196: @27 = (-@27) */
  for (i=0, rr=w27, cs=w27; i<2; ++i) *rr++ = (- *cs++ );
  /* #197: (@26[:2] += @27) */
  for (rr=w26+0, ss=w27; rr!=w26+2; rr+=1) *rr += *ss++;
  /* #198: {@8, @15, @14, @19, @2, @3} = vertsplit(@26) */
  w8 = w26[0];
  w15 = w26[1];
  w14 = w26[2];
  w19 = w26[3];
  w2 = w26[4];
  w3 = w26[5];
  /* #199: @40 = cos(@1) */
  w40 = cos( w1 );
  /* #200: @40 = (@40*@16) */
  w40 *= w16;
  /* #201: @21 = (@21*@40) */
  w21 *= w40;
  /* #202: @21 = (-@21) */
  w21 = (- w21 );
  /* #203: @40 = sin(@1) */
  w40 = sin( w1 );
  /* #204: @40 = (@40*@16) */
  w40 *= w16;
  /* #205: @18 = (@18*@40) */
  w18 *= w40;
  /* #206: @21 = (@21-@18) */
  w21 -= w18;
  /* #207: @18 = sin(@1) */
  w18 = sin( w1 );
  /* #208: @18 = (@18*@16) */
  w18 *= w16;
  /* #209: @11 = (@11*@18) */
  w11 *= w18;
  /* #210: @21 = (@21+@11) */
  w21 += w11;
  /* #211: @11 = cos(@1) */
  w11 = cos( w1 );
  /* #212: @11 = (@11*@16) */
  w11 *= w16;
  /* #213: @10 = (@10*@11) */
  w10 *= w11;
  /* #214: @21 = (@21-@10) */
  w21 -= w10;
  /* #215: @21 = (@21+@14) */
  w21 += w14;
  /* #216: @14 = (-@16) */
  w14 = (- w16 );
  /* #217: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #218: @21 = (@21-@14) */
  w21 -= w14;
  /* #219: @14 = cos(@1) */
  w14 = cos( w1 );
  /* #220: @14 = (@14*@16) */
  w14 *= w16;
  /* #221: @14 = (@17*@14) */
  w14  = (w17*w14);
  /* #222: @10 = sin(@1) */
  w10 = sin( w1 );
  /* #223: @10 = (@10*@16) */
  w10 *= w16;
  /* #224: @10 = (@9*@10) */
  w10  = (w9*w10);
  /* #225: @14 = (@14-@10) */
  w14 -= w10;
  /* #226: @14 = (@14+@19) */
  w14 += w19;
  /* #227: @19 = cos(@1) */
  w19 = cos( w1 );
  /* #228: @19 = (@19*@16) */
  w19 *= w16;
  /* #229: @19 = (@9*@19) */
  w19  = (w9*w19);
  /* #230: @19 = (-@19) */
  w19 = (- w19 );
  /* #231: @1 = sin(@1) */
  w1 = sin( w1 );
  /* #232: @1 = (@1*@16) */
  w1 *= w16;
  /* #233: @1 = (@17*@1) */
  w1  = (w17*w1);
  /* #234: @19 = (@19-@1) */
  w19 -= w1;
  /* #235: @19 = (@19+@2) */
  w19 += w2;
  /* #236: @45 = vertcat(@12, @0, @13, @8, @15, @21, @14, @19, @3) */
  rr=w45;
  *rr++ = w12;
  *rr++ = w0;
  *rr++ = w13;
  *rr++ = w8;
  *rr++ = w15;
  *rr++ = w21;
  *rr++ = w14;
  *rr++ = w19;
  *rr++ = w3;
  /* #237: @46 = @45[:8] */
  for (rr=w46, ss=w45+0; ss!=w45+8; ss+=1) *rr++ = *ss;
  /* #238: (@41[0, 1, 2, 9, 10, 13, 14, 15] = @46) */
  for (cii=casadi_s7, rr=w41, ss=w46; cii!=casadi_s7+8; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #239: @46 = @45[:8] */
  for (rr=w46, ss=w45+0; ss!=w45+8; ss+=1) *rr++ = *ss;
  /* #240: (@41[0, 3, 6, 9, 11, 13, 16, 17] = @46) */
  for (cii=casadi_s8, rr=w41, ss=w46; cii!=casadi_s8+8; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #241: @30 = zeros(1x3) */
  casadi_clear(w30, 3);
  /* #242: @43 = 00 */
  /* #243: @42 = ones(9x1,4nz) */
  casadi_fill(w42, 4, 1.);
  /* #244: {NULL, @12, NULL, NULL, @0, NULL, @13, @8, NULL} = vertsplit(@42) */
  w12 = w42[0];
  w0 = w42[1];
  w13 = w42[2];
  w8 = w42[3];
  /* #245: @44 = 00 */
  /* #246: @15 = vertcat(@43, @12, @44) */
  rr=(&w15);
  *rr++ = w12;
  /* #247: @12 = @15' */
  casadi_copy((&w15), 1, (&w12));
  /* #248: @30 = mac(@12,@33,@30) */
  casadi_mtimes((&w12), casadi_s9, w33, casadi_s2, w30, casadi_s1, w, 0);
  /* #249: @30 = @30' */
  /* #250: @32 = zeros(1x3) */
  casadi_clear(w32, 3);
  /* #251: @15 = @15' */
  /* #252: @32 = mac(@15,@34,@32) */
  casadi_mtimes((&w15), casadi_s9, w34, casadi_s2, w32, casadi_s1, w, 0);
  /* #253: @32 = @32' */
  /* #254: @30 = (@30+@32) */
  for (i=0, rr=w30, cs=w32; i<3; ++i) (*rr++) += (*cs++);
  /* #255: {@15, @12, @21} = vertsplit(@30) */
  w15 = w30[0];
  w12 = w30[1];
  w21 = w30[2];
  /* #256: @26 = zeros(6x1) */
  casadi_clear(w26, 6);
  /* #257: @27 = zeros(1x2) */
  casadi_clear(w27, 2);
  /* #258: @14 = project(@23) */
  casadi_sparsify(w23, (&w14), casadi_s10, 0);
  /* #259: @19 = @0[0] */
  for (rr=(&w19), ss=(&w0)+0; ss!=(&w0)+1; ss+=1) *rr++ = *ss;
  /* #260: @19 = (-@19) */
  w19 = (- w19 );
  /* #261: @0 = dot(@14, @19) */
  w0 = casadi_dot(1, (&w14), (&w19));
  /* #262: @5 = (@23*@0) */
  for (i=0, rr=w5, cr=w23; i<2; ++i) (*rr++)  = ((*cr++)*w0);
  /* #263: @28 = @5' */
  casadi_copy(w5, 2, w28);
  /* #264: @27 = mac(@28,@29,@27) */
  for (i=0, rr=w27; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w28+j, tt=w29+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #265: @27 = @27' */
  /* #266: @28 = zeros(1x2) */
  casadi_clear(w28, 2);
  /* #267: @5 = @5' */
  /* #268: @28 = mac(@5,@35,@28) */
  for (i=0, rr=w28; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w5+j, tt=w35+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #269: @28 = @28' */
  /* #270: @27 = (@27+@28) */
  for (i=0, rr=w27, cs=w28; i<2; ++i) (*rr++) += (*cs++);
  /* #271: @0 = dot(@23, @27) */
  w0 = casadi_dot(2, w23, w27);
  /* #272: @23 = (@23*@0) */
  for (i=0, rr=w23; i<2; ++i) (*rr++) *= w0;
  /* #273: @27 = zeros(2x1) */
  casadi_clear(w27, 2);
  /* #274: @28 = zeros(1x2) */
  casadi_clear(w28, 2);
  /* #275: @5 = zeros(2x1) */
  casadi_clear(w5, 2);
  /* #276: @5 = mac(@7,@19,@5) */
  casadi_mtimes(w7, casadi_s6, (&w19), casadi_s10, w5, casadi_s5, w, 0);
  /* #277: @6 = @5' */
  casadi_copy(w5, 2, w6);
  /* #278: @28 = mac(@6,@25,@28) */
  for (i=0, rr=w28; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w6+j, tt=w25+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #279: @28 = @28' */
  /* #280: @6 = zeros(1x2) */
  casadi_clear(w6, 2);
  /* #281: @5 = @5' */
  /* #282: @6 = mac(@5,@37,@6) */
  for (i=0, rr=w6; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w5+j, tt=w37+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #283: @6 = @6' */
  /* #284: @28 = (@28+@6) */
  for (i=0, rr=w28, cs=w6; i<2; ++i) (*rr++) += (*cs++);
  /* #285: @27 = mac(@36,@28,@27) */
  for (i=0, rr=w27; i<1; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w36+j, tt=w28+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #286: @23 = (@23+@27) */
  for (i=0, rr=w23, cs=w27; i<2; ++i) (*rr++) += (*cs++);
  /* #287: @23 = (-@23) */
  for (i=0, rr=w23, cs=w23; i<2; ++i) *rr++ = (- *cs++ );
  /* #288: (@26[:2] += @23) */
  for (rr=w26+0, ss=w23; rr!=w26+2; rr+=1) *rr += *ss++;
  /* #289: {@19, @0, @14, @3, @2, @1} = vertsplit(@26) */
  w19 = w26[0];
  w0 = w26[1];
  w14 = w26[2];
  w3 = w26[3];
  w2 = w26[4];
  w1 = w26[5];
  /* #290: @16 = (@17*@13) */
  w16  = (w17*w13);
  /* #291: @4 = (@4*@16) */
  w4 *= w16;
  /* #292: @17 = (@17*@8) */
  w17 *= w8;
  /* #293: @20 = (@20*@17) */
  w20 *= w17;
  /* #294: @4 = (@4-@20) */
  w4 -= w20;
  /* #295: @8 = (@9*@8) */
  w8  = (w9*w8);
  /* #296: @38 = (@38*@8) */
  w38 *= w8;
  /* #297: @4 = (@4-@38) */
  w4 -= w38;
  /* #298: @9 = (@9*@13) */
  w9 *= w13;
  /* #299: @39 = (@39*@9) */
  w39 *= w9;
  /* #300: @4 = (@4-@39) */
  w4 -= w39;
  /* #301: @4 = (@4+@14) */
  w4 += w14;
  /* #302: @45 = vertcat(@15, @12, @21, @19, @0, @4, @3, @2, @1) */
  rr=w45;
  *rr++ = w15;
  *rr++ = w12;
  *rr++ = w21;
  *rr++ = w19;
  *rr++ = w0;
  *rr++ = w4;
  *rr++ = w3;
  *rr++ = w2;
  *rr++ = w1;
  /* #303: @47 = @45[:5] */
  for (rr=w47, ss=w45+0; ss!=w45+5; ss+=1) *rr++ = *ss;
  /* #304: (@41[3, 4, 5, 11, 12] = @47) */
  for (cii=casadi_s11, rr=w41, ss=w47; cii!=casadi_s11+5; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #305: @47 = @45[:5] */
  for (rr=w47, ss=w45+0; ss!=w45+5; ss+=1) *rr++ = *ss;
  /* #306: (@41[1, 4, 7, 10, 12] = @47) */
  for (cii=casadi_s12, rr=w41, ss=w47; cii!=casadi_s12+5; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #307: @30 = zeros(1x3) */
  casadi_clear(w30, 3);
  /* #308: @43 = 00 */
  /* #309: @44 = 00 */
  /* #310: @15 = ones(9x1,1nz) */
  w15 = 1.;
  /* #311: {NULL, NULL, @12, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@15) */
  w12 = w15;
  /* #312: @15 = vertcat(@43, @44, @12) */
  rr=(&w15);
  *rr++ = w12;
  /* #313: @12 = @15' */
  casadi_copy((&w15), 1, (&w12));
  /* #314: @30 = mac(@12,@33,@30) */
  casadi_mtimes((&w12), casadi_s13, w33, casadi_s2, w30, casadi_s1, w, 0);
  /* #315: @30 = @30' */
  /* #316: @32 = zeros(1x3) */
  casadi_clear(w32, 3);
  /* #317: @15 = @15' */
  /* #318: @32 = mac(@15,@34,@32) */
  casadi_mtimes((&w15), casadi_s13, w34, casadi_s2, w32, casadi_s1, w, 0);
  /* #319: @32 = @32' */
  /* #320: @30 = (@30+@32) */
  for (i=0, rr=w30, cs=w32; i<3; ++i) (*rr++) += (*cs++);
  /* #321: {@15, @12, @21} = vertsplit(@30) */
  w15 = w30[0];
  w12 = w30[1];
  w21 = w30[2];
  /* #322: @43 = 00 */
  /* #323: @44 = 00 */
  /* #324: @48 = 00 */
  /* #325: @49 = 00 */
  /* #326: @50 = 00 */
  /* #327: @51 = 00 */
  /* #328: @30 = vertcat(@15, @12, @21, @43, @44, @48, @49, @50, @51) */
  rr=w30;
  *rr++ = w15;
  *rr++ = w12;
  *rr++ = w21;
  /* #329: @32 = @30[:3] */
  for (rr=w32, ss=w30+0; ss!=w30+3; ss+=1) *rr++ = *ss;
  /* #330: (@41[6:9] = @32) */
  for (rr=w41+6, ss=w32; rr!=w41+9; rr+=1) *rr = *ss++;
  /* #331: @32 = @30[:3] */
  for (rr=w32, ss=w30+0; ss!=w30+3; ss+=1) *rr++ = *ss;
  /* #332: (@41[2:11:3] = @32) */
  for (rr=w41+2, ss=w32; rr!=w41+11; rr+=3) *rr = *ss++;
  /* #333: @52 = @41' */
  casadi_trans(w41,casadi_s14, w52, casadi_s14, iw);
  /* #334: output[2][0] = @52 */
  casadi_copy(w52, 18, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int USV_ode_cost_ext_cost_0_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int USV_ode_cost_ext_cost_0_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int USV_ode_cost_ext_cost_0_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void USV_ode_cost_ext_cost_0_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int USV_ode_cost_ext_cost_0_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void USV_ode_cost_ext_cost_0_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void USV_ode_cost_ext_cost_0_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void USV_ode_cost_ext_cost_0_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int USV_ode_cost_ext_cost_0_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int USV_ode_cost_ext_cost_0_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real USV_ode_cost_ext_cost_0_fun_jac_hess_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* USV_ode_cost_ext_cost_0_fun_jac_hess_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* USV_ode_cost_ext_cost_0_fun_jac_hess_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* USV_ode_cost_ext_cost_0_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s15;
    case 1: return casadi_s16;
    case 2: return casadi_s17;
    case 3: return casadi_s18;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* USV_ode_cost_ext_cost_0_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s19;
    case 1: return casadi_s20;
    case 2: return casadi_s14;
    case 3: return casadi_s21;
    case 4: return casadi_s22;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int USV_ode_cost_ext_cost_0_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 18;
  if (sz_res) *sz_res = 14;
  if (sz_iw) *sz_iw = 10;
  if (sz_w) *sz_w = 169;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
