/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) USV_ode_cost_ext_cost_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

static const casadi_int casadi_s0[4] = {0, 0, 0, 0};
static const casadi_int casadi_s1[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s2[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s3[4] = {0, 1, 0, 0};
static const casadi_int casadi_s4[18] = {14, 1, 0, 14, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13};
static const casadi_int casadi_s5[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s6[13] = {9, 1, 0, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8};

static const casadi_real casadi_c0[4] = {1., 0., 0., 1.};
static const casadi_real casadi_c1[4] = {5., 0., 0., 5.};
static const casadi_real casadi_c2[9] = {1.0000000000000000e-04, 0., 0., 0., 1.0000000000000000e-04, 0., 0., 0., 1.0000000000000000e-04};

/* USV_ode_cost_ext_cost_fun_jac:(i0[6],i1[3],i2[0],i3[14])->(o0,o1[9]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_int *cii;
  const casadi_real *cs;
  casadi_real w0, w1, w2, w3, w4, *w5=w+7, *w6=w+9, *w7=w+11, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, *w22=w+29, *w23=w+43, *w24=w+45, *w25=w+47, *w26=w+51, *w27=w+57, *w28=w+59, *w29=w+61, *w30=w+65, *w31=w+68, *w32=w+71, *w33=w+74, *w34=w+83, *w35=w+92;
  /* #0: @0 = input[3][8] */
  w0 = arg[3] ? arg[3][8] : 0;
  /* #1: @1 = input[0][2] */
  w1 = arg[0] ? arg[0][2] : 0;
  /* #2: @2 = (@0-@1) */
  w2  = (w0-w1);
  /* #3: @3 = sq(@2) */
  w3 = casadi_sq( w2 );
  /* #4: @4 = 0 */
  w4 = 0.;
  /* #5: @5 = zeros(1x2) */
  casadi_clear(w5, 2);
  /* #6: @6 = zeros(2x1) */
  casadi_clear(w6, 2);
  /* #7: @7 = 
  [[1, 0], 
   [0, 1]] */
  casadi_copy(casadi_c0, 4, w7);
  /* #8: @8 = 0 */
  w8 = 0.;
  /* #9: @9 = input[3][0] */
  w9 = arg[3] ? arg[3][0] : 0;
  /* #10: @10 = input[3][1] */
  w10 = arg[3] ? arg[3][1] : 0;
  /* #11: @11 = input[3][2] */
  w11 = arg[3] ? arg[3][2] : 0;
  /* #12: @12 = input[3][3] */
  w12 = arg[3] ? arg[3][3] : 0;
  /* #13: @13 = input[3][4] */
  w13 = arg[3] ? arg[3][4] : 0;
  /* #14: @14 = input[3][5] */
  w14 = arg[3] ? arg[3][5] : 0;
  /* #15: @15 = input[3][6] */
  w15 = arg[3] ? arg[3][6] : 0;
  /* #16: @16 = input[3][7] */
  w16 = arg[3] ? arg[3][7] : 0;
  /* #17: @17 = input[3][9] */
  w17 = arg[3] ? arg[3][9] : 0;
  /* #18: @18 = input[3][10] */
  w18 = arg[3] ? arg[3][10] : 0;
  /* #19: @19 = input[3][11] */
  w19 = arg[3] ? arg[3][11] : 0;
  /* #20: @20 = input[3][12] */
  w20 = arg[3] ? arg[3][12] : 0;
  /* #21: @21 = input[3][13] */
  w21 = arg[3] ? arg[3][13] : 0;
  /* #22: @22 = vertcat(@9, @10, @11, @12, @13, @14, @15, @16, @0, @17, @18, @19, @20, @21) */
  rr=w22;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w0;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w20;
  *rr++ = w21;
  /* #23: @23 = @22[3:5] */
  for (rr=w23, ss=w22+3; ss!=w22+5; ss+=1) *rr++ = *ss;
  /* #24: @24 = @23' */
  casadi_copy(w23, 2, w24);
  /* #25: @8 = mac(@24,@23,@8) */
  for (i=0, rr=(&w8); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w24+j, tt=w23+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #26: @25 = @8[0, 0, 0, 0] */
  for (cii=casadi_s0, rr=w25, ss=(&w8); cii!=casadi_s0+4; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #27: @7 = (@7-@25) */
  for (i=0, rr=w7, cs=w25; i<4; ++i) (*rr++) -= (*cs++);
  /* #28: @24 = @22[:2] */
  for (rr=w24, ss=w22+0; ss!=w22+2; ss+=1) *rr++ = *ss;
  /* #29: @8 = input[0][0] */
  w8 = arg[0] ? arg[0][0] : 0;
  /* #30: @9 = input[0][1] */
  w9 = arg[0] ? arg[0][1] : 0;
  /* #31: @10 = input[0][3] */
  w10 = arg[0] ? arg[0][3] : 0;
  /* #32: @11 = input[0][4] */
  w11 = arg[0] ? arg[0][4] : 0;
  /* #33: @12 = input[0][5] */
  w12 = arg[0] ? arg[0][5] : 0;
  /* #34: @26 = vertcat(@8, @9, @1, @10, @11, @12) */
  rr=w26;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w1;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  /* #35: @27 = @26[:2] */
  for (rr=w27, ss=w26+0; ss!=w26+2; ss+=1) *rr++ = *ss;
  /* #36: @24 = (@24-@27) */
  for (i=0, rr=w24, cs=w27; i<2; ++i) (*rr++) -= (*cs++);
  /* #37: @6 = mac(@7,@24,@6) */
  for (i=0, rr=w6; i<1; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w7+j, tt=w24+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #38: @27 = @6' */
  casadi_copy(w6, 2, w27);
  /* #39: @25 = 
  [[5, 0], 
   [0, 5]] */
  casadi_copy(casadi_c1, 4, w25);
  /* #40: @5 = mac(@27,@25,@5) */
  for (i=0, rr=w5; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w27+j, tt=w25+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #41: @4 = mac(@5,@6,@4) */
  for (i=0, rr=(&w4); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w5+j, tt=w6+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #42: @8 = 0 */
  w8 = 0.;
  /* #43: @27 = zeros(1x2) */
  casadi_clear(w27, 2);
  /* #44: @9 = dot(@23, @24) */
  w9 = casadi_dot(2, w23, w24);
  /* #45: @24 = (@9*@23) */
  for (i=0, rr=w24, cs=w23; i<2; ++i) (*rr++)  = (w9*(*cs++));
  /* #46: @28 = @24' */
  casadi_copy(w24, 2, w28);
  /* #47: @29 = 
  [[5, 0], 
   [0, 5]] */
  casadi_copy(casadi_c1, 4, w29);
  /* #48: @27 = mac(@28,@29,@27) */
  for (i=0, rr=w27; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w28+j, tt=w29+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #49: @8 = mac(@27,@24,@8) */
  for (i=0, rr=(&w8); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w27+j, tt=w24+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #50: @4 = (@4+@8) */
  w4 += w8;
  /* #51: @3 = (@3+@4) */
  w3 += w4;
  /* #52: @4 = 0.01 */
  w4 = 1.0000000000000000e-02;
  /* #53: @8 = cos(@1) */
  w8 = cos( w1 );
  /* #54: @9 = (@10*@8) */
  w9  = (w10*w8);
  /* #55: @12 = sin(@1) */
  w12 = sin( w1 );
  /* #56: @13 = (@11*@12) */
  w13  = (w11*w12);
  /* #57: @9 = (@9-@13) */
  w9 -= w13;
  /* #58: @13 = sin(@1) */
  w13 = sin( w1 );
  /* #59: @14 = (@10*@13) */
  w14  = (w10*w13);
  /* #60: @15 = cos(@1) */
  w15 = cos( w1 );
  /* #61: @16 = (@11*@15) */
  w16  = (w11*w15);
  /* #62: @14 = (@14+@16) */
  w14 += w16;
  /* #63: @28 = vertcat(@9, @14) */
  rr=w28;
  *rr++ = w9;
  *rr++ = w14;
  /* #64: @9 = dot(@23, @28) */
  w9 = casadi_dot(2, w23, w28);
  /* #65: @4 = (@4*@9) */
  w4 *= w9;
  /* #66: @3 = (@3-@4) */
  w3 -= w4;
  /* #67: @4 = 0 */
  w4 = 0.;
  /* #68: @30 = zeros(1x3) */
  casadi_clear(w30, 3);
  /* #69: @9 = input[1][0] */
  w9 = arg[1] ? arg[1][0] : 0;
  /* #70: @14 = input[1][1] */
  w14 = arg[1] ? arg[1][1] : 0;
  /* #71: @16 = input[1][2] */
  w16 = arg[1] ? arg[1][2] : 0;
  /* #72: @31 = vertcat(@9, @14, @16) */
  rr=w31;
  *rr++ = w9;
  *rr++ = w14;
  *rr++ = w16;
  /* #73: @32 = @31' */
  casadi_copy(w31, 3, w32);
  /* #74: @33 = 
  [[0.0001, 0, 0], 
   [0, 0.0001, 0], 
   [0, 0, 0.0001]] */
  casadi_copy(casadi_c2, 9, w33);
  /* #75: @30 = mac(@32,@33,@30) */
  for (i=0, rr=w30; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w32+j, tt=w33+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #76: @4 = mac(@30,@31,@4) */
  for (i=0, rr=(&w4); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w30+j, tt=w31+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #77: @3 = (@3+@4) */
  w3 += w4;
  /* #78: output[0][0] = @3 */
  if (res[0]) res[0][0] = w3;
  /* #79: @30 = @30' */
  /* #80: @32 = zeros(1x3) */
  casadi_clear(w32, 3);
  /* #81: @31 = @31' */
  /* #82: @34 = @33' */
  for (i=0, rr=w34, cs=w33; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #83: @32 = mac(@31,@34,@32) */
  for (i=0, rr=w32; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w31+j, tt=w34+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #84: @32 = @32' */
  /* #85: @30 = (@30+@32) */
  for (i=0, rr=w30, cs=w32; i<3; ++i) (*rr++) += (*cs++);
  /* #86: {@3, @4, @9} = vertsplit(@30) */
  w3 = w30[0];
  w4 = w30[1];
  w9 = w30[2];
  /* #87: output[1][0] = @3 */
  if (res[1]) res[1][0] = w3;
  /* #88: output[1][1] = @4 */
  if (res[1]) res[1][1] = w4;
  /* #89: output[1][2] = @9 */
  if (res[1]) res[1][2] = w9;
  /* #90: @26 = zeros(6x1) */
  casadi_clear(w26, 6);
  /* #91: @27 = @27' */
  /* #92: @28 = zeros(1x2) */
  casadi_clear(w28, 2);
  /* #93: @24 = @24' */
  /* #94: @35 = @29' */
  for (i=0, rr=w35, cs=w29; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #95: @28 = mac(@24,@35,@28) */
  for (i=0, rr=w28; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w24+j, tt=w35+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #96: @28 = @28' */
  /* #97: @27 = (@27+@28) */
  for (i=0, rr=w27, cs=w28; i<2; ++i) (*rr++) += (*cs++);
  /* #98: @9 = dot(@23, @27) */
  w9 = casadi_dot(2, w23, w27);
  /* #99: @27 = (@9*@23) */
  for (i=0, rr=w27, cs=w23; i<2; ++i) (*rr++)  = (w9*(*cs++));
  /* #100: @28 = zeros(2x1) */
  casadi_clear(w28, 2);
  /* #101: @35 = @7' */
  for (i=0, rr=w35, cs=w7; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #102: @5 = @5' */
  /* #103: @24 = zeros(1x2) */
  casadi_clear(w24, 2);
  /* #104: @6 = @6' */
  /* #105: @7 = @25' */
  for (i=0, rr=w7, cs=w25; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #106: @24 = mac(@6,@7,@24) */
  for (i=0, rr=w24; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w6+j, tt=w7+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #107: @24 = @24' */
  /* #108: @5 = (@5+@24) */
  for (i=0, rr=w5, cs=w24; i<2; ++i) (*rr++) += (*cs++);
  /* #109: @28 = mac(@35,@5,@28) */
  for (i=0, rr=w28; i<1; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w35+j, tt=w5+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #110: @27 = (@27+@28) */
  for (i=0, rr=w27, cs=w28; i<2; ++i) (*rr++) += (*cs++);
  /* #111: @27 = (-@27) */
  for (i=0, rr=w27, cs=w27; i<2; ++i) *rr++ = (- *cs++ );
  /* #112: (@26[:2] += @27) */
  for (rr=w26+0, ss=w27; rr!=w26+2; rr+=1) *rr += *ss++;
  /* #113: {@9, @4, @3, @14, @16, @0} = vertsplit(@26) */
  w9 = w26[0];
  w4 = w26[1];
  w3 = w26[2];
  w14 = w26[3];
  w16 = w26[4];
  w0 = w26[5];
  /* #114: output[1][3] = @9 */
  if (res[1]) res[1][3] = w9;
  /* #115: output[1][4] = @4 */
  if (res[1]) res[1][4] = w4;
  /* #116: @4 = cos(@1) */
  w4 = cos( w1 );
  /* #117: @9 = -0.01 */
  w9 = -1.0000000000000000e-02;
  /* #118: @23 = (@9*@23) */
  for (i=0, rr=w23, cs=w23; i<2; ++i) (*rr++)  = (w9*(*cs++));
  /* #119: {@9, @17} = vertsplit(@23) */
  w9 = w23[0];
  w17 = w23[1];
  /* #120: @18 = (@10*@17) */
  w18  = (w10*w17);
  /* #121: @4 = (@4*@18) */
  w4 *= w18;
  /* #122: @18 = sin(@1) */
  w18 = sin( w1 );
  /* #123: @19 = (@11*@17) */
  w19  = (w11*w17);
  /* #124: @18 = (@18*@19) */
  w18 *= w19;
  /* #125: @4 = (@4-@18) */
  w4 -= w18;
  /* #126: @18 = cos(@1) */
  w18 = cos( w1 );
  /* #127: @11 = (@11*@9) */
  w11 *= w9;
  /* #128: @18 = (@18*@11) */
  w18 *= w11;
  /* #129: @4 = (@4-@18) */
  w4 -= w18;
  /* #130: @1 = sin(@1) */
  w1 = sin( w1 );
  /* #131: @10 = (@10*@9) */
  w10 *= w9;
  /* #132: @1 = (@1*@10) */
  w1 *= w10;
  /* #133: @4 = (@4-@1) */
  w4 -= w1;
  /* #134: @4 = (@4+@3) */
  w4 += w3;
  /* #135: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #136: @4 = (@4-@2) */
  w4 -= w2;
  /* #137: output[1][5] = @4 */
  if (res[1]) res[1][5] = w4;
  /* #138: @13 = (@13*@17) */
  w13 *= w17;
  /* #139: @8 = (@8*@9) */
  w8 *= w9;
  /* #140: @13 = (@13+@8) */
  w13 += w8;
  /* #141: @13 = (@13+@14) */
  w13 += w14;
  /* #142: output[1][6] = @13 */
  if (res[1]) res[1][6] = w13;
  /* #143: @15 = (@15*@17) */
  w15 *= w17;
  /* #144: @12 = (@12*@9) */
  w12 *= w9;
  /* #145: @15 = (@15-@12) */
  w15 -= w12;
  /* #146: @15 = (@15+@16) */
  w15 += w16;
  /* #147: output[1][7] = @15 */
  if (res[1]) res[1][7] = w15;
  /* #148: output[1][8] = @0 */
  if (res[1]) res[1][8] = w0;
  return 0;
}

CASADI_SYMBOL_EXPORT int USV_ode_cost_ext_cost_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int USV_ode_cost_ext_cost_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int USV_ode_cost_ext_cost_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void USV_ode_cost_ext_cost_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int USV_ode_cost_ext_cost_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void USV_ode_cost_ext_cost_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void USV_ode_cost_ext_cost_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void USV_ode_cost_ext_cost_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int USV_ode_cost_ext_cost_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int USV_ode_cost_ext_cost_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real USV_ode_cost_ext_cost_fun_jac_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* USV_ode_cost_ext_cost_fun_jac_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* USV_ode_cost_ext_cost_fun_jac_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* USV_ode_cost_ext_cost_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    case 2: return casadi_s3;
    case 3: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* USV_ode_cost_ext_cost_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int USV_ode_cost_ext_cost_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 18;
  if (sz_res) *sz_res = 8;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 96;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
