/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) USV_ode_cost_ext_cost_e_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sparsify CASADI_PREFIX(sparsify)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_sparsify(const casadi_real* x, casadi_real* y, const casadi_int* sp_y, casadi_int tr) {
  casadi_int nrow_y, ncol_y, i, el;
  const casadi_int *colind_y, *row_y;
  nrow_y = sp_y[0];
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y+ncol_y+3;
  if (tr) {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[i + row_y[el]*ncol_y]);
      }
    }
  } else {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[row_y[el]]);
      }
      x += nrow_y;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[4] = {0, 0, 0, 0};
static const casadi_int casadi_s1[5] = {2, 1, 0, 1, 0};
static const casadi_int casadi_s2[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s3[9] = {2, 2, 0, 2, 4, 0, 1, 0, 1};
static const casadi_int casadi_s4[5] = {0, 1, 4, 5, 6};
static const casadi_int casadi_s5[5] = {0, 2, 4, 7, 8};
static const casadi_int casadi_s6[5] = {2, 1, 0, 1, 1};
static const casadi_int casadi_s7[18] = {6, 6, 0, 2, 4, 7, 8, 9, 9, 0, 1, 0, 1, 2, 3, 4, 2, 2};
static const casadi_int casadi_s8[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s9[3] = {0, 0, 0};
static const casadi_int casadi_s10[18] = {14, 1, 0, 14, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13};
static const casadi_int casadi_s11[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s12[9] = {0, 6, 0, 0, 0, 0, 0, 0, 0};

static const casadi_real casadi_c0[4] = {1., 0., 0., 1.};
static const casadi_real casadi_c1[4] = {5., 0., 0., 5.};

/* USV_ode_cost_ext_cost_e_fun_jac_hess:(i0[6],i1[],i2[],i3[14])->(o0,o1[6],o2[6x6,9nz],o3[],o4[0x6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_int *cii;
  const casadi_real *cr, *cs;
  casadi_real w0, w1, w2, w3, w4, *w5=w+7, *w6=w+9, *w7=w+11, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, *w22=w+29, *w23=w+43, *w24=w+45, *w25=w+47, *w26=w+51, *w27=w+57, *w28=w+59, *w29=w+61, *w30=w+65, *w31=w+69, *w32=w+73, w33, w34, w35, *w36=w+80, *w37=w+89, *w38=w+92, *w39=w+97;
  /* #0: @0 = input[3][8] */
  w0 = arg[3] ? arg[3][8] : 0;
  /* #1: @1 = input[0][2] */
  w1 = arg[0] ? arg[0][2] : 0;
  /* #2: @2 = (@0-@1) */
  w2  = (w0-w1);
  /* #3: @3 = sq(@2) */
  w3 = casadi_sq( w2 );
  /* #4: @4 = 0 */
  w4 = 0.;
  /* #5: @5 = zeros(1x2) */
  casadi_clear(w5, 2);
  /* #6: @6 = zeros(2x1) */
  casadi_clear(w6, 2);
  /* #7: @7 = 
  [[1, 0], 
   [0, 1]] */
  casadi_copy(casadi_c0, 4, w7);
  /* #8: @8 = 0 */
  w8 = 0.;
  /* #9: @9 = input[3][0] */
  w9 = arg[3] ? arg[3][0] : 0;
  /* #10: @10 = input[3][1] */
  w10 = arg[3] ? arg[3][1] : 0;
  /* #11: @11 = input[3][2] */
  w11 = arg[3] ? arg[3][2] : 0;
  /* #12: @12 = input[3][3] */
  w12 = arg[3] ? arg[3][3] : 0;
  /* #13: @13 = input[3][4] */
  w13 = arg[3] ? arg[3][4] : 0;
  /* #14: @14 = input[3][5] */
  w14 = arg[3] ? arg[3][5] : 0;
  /* #15: @15 = input[3][6] */
  w15 = arg[3] ? arg[3][6] : 0;
  /* #16: @16 = input[3][7] */
  w16 = arg[3] ? arg[3][7] : 0;
  /* #17: @17 = input[3][9] */
  w17 = arg[3] ? arg[3][9] : 0;
  /* #18: @18 = input[3][10] */
  w18 = arg[3] ? arg[3][10] : 0;
  /* #19: @19 = input[3][11] */
  w19 = arg[3] ? arg[3][11] : 0;
  /* #20: @20 = input[3][12] */
  w20 = arg[3] ? arg[3][12] : 0;
  /* #21: @21 = input[3][13] */
  w21 = arg[3] ? arg[3][13] : 0;
  /* #22: @22 = vertcat(@9, @10, @11, @12, @13, @14, @15, @16, @0, @17, @18, @19, @20, @21) */
  rr=w22;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w0;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w20;
  *rr++ = w21;
  /* #23: @23 = @22[3:5] */
  for (rr=w23, ss=w22+3; ss!=w22+5; ss+=1) *rr++ = *ss;
  /* #24: @24 = @23' */
  casadi_copy(w23, 2, w24);
  /* #25: @8 = mac(@24,@23,@8) */
  for (i=0, rr=(&w8); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w24+j, tt=w23+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #26: @25 = @8[0, 0, 0, 0] */
  for (cii=casadi_s0, rr=w25, ss=(&w8); cii!=casadi_s0+4; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #27: @7 = (@7-@25) */
  for (i=0, rr=w7, cs=w25; i<4; ++i) (*rr++) -= (*cs++);
  /* #28: @24 = @22[:2] */
  for (rr=w24, ss=w22+0; ss!=w22+2; ss+=1) *rr++ = *ss;
  /* #29: @8 = input[0][0] */
  w8 = arg[0] ? arg[0][0] : 0;
  /* #30: @9 = input[0][1] */
  w9 = arg[0] ? arg[0][1] : 0;
  /* #31: @10 = input[0][3] */
  w10 = arg[0] ? arg[0][3] : 0;
  /* #32: @11 = input[0][4] */
  w11 = arg[0] ? arg[0][4] : 0;
  /* #33: @12 = input[0][5] */
  w12 = arg[0] ? arg[0][5] : 0;
  /* #34: @26 = vertcat(@8, @9, @1, @10, @11, @12) */
  rr=w26;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w1;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  /* #35: @27 = @26[:2] */
  for (rr=w27, ss=w26+0; ss!=w26+2; ss+=1) *rr++ = *ss;
  /* #36: @24 = (@24-@27) */
  for (i=0, rr=w24, cs=w27; i<2; ++i) (*rr++) -= (*cs++);
  /* #37: @6 = mac(@7,@24,@6) */
  for (i=0, rr=w6; i<1; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w7+j, tt=w24+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #38: @27 = @6' */
  casadi_copy(w6, 2, w27);
  /* #39: @25 = 
  [[5, 0], 
   [0, 5]] */
  casadi_copy(casadi_c1, 4, w25);
  /* #40: @5 = mac(@27,@25,@5) */
  for (i=0, rr=w5; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w27+j, tt=w25+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #41: @4 = mac(@5,@6,@4) */
  for (i=0, rr=(&w4); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w5+j, tt=w6+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #42: @8 = 0 */
  w8 = 0.;
  /* #43: @27 = zeros(1x2) */
  casadi_clear(w27, 2);
  /* #44: @9 = dot(@23, @24) */
  w9 = casadi_dot(2, w23, w24);
  /* #45: @24 = (@9*@23) */
  for (i=0, rr=w24, cs=w23; i<2; ++i) (*rr++)  = (w9*(*cs++));
  /* #46: @28 = @24' */
  casadi_copy(w24, 2, w28);
  /* #47: @29 = 
  [[5, 0], 
   [0, 5]] */
  casadi_copy(casadi_c1, 4, w29);
  /* #48: @27 = mac(@28,@29,@27) */
  for (i=0, rr=w27; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w28+j, tt=w29+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #49: @8 = mac(@27,@24,@8) */
  for (i=0, rr=(&w8); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w27+j, tt=w24+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #50: @4 = (@4+@8) */
  w4 += w8;
  /* #51: @3 = (@3+@4) */
  w3 += w4;
  /* #52: @4 = 0.01 */
  w4 = 1.0000000000000000e-02;
  /* #53: @8 = cos(@1) */
  w8 = cos( w1 );
  /* #54: @9 = (@10*@8) */
  w9  = (w10*w8);
  /* #55: @12 = sin(@1) */
  w12 = sin( w1 );
  /* #56: @13 = (@11*@12) */
  w13  = (w11*w12);
  /* #57: @9 = (@9-@13) */
  w9 -= w13;
  /* #58: @13 = sin(@1) */
  w13 = sin( w1 );
  /* #59: @14 = (@10*@13) */
  w14  = (w10*w13);
  /* #60: @15 = cos(@1) */
  w15 = cos( w1 );
  /* #61: @16 = (@11*@15) */
  w16  = (w11*w15);
  /* #62: @14 = (@14+@16) */
  w14 += w16;
  /* #63: @28 = vertcat(@9, @14) */
  rr=w28;
  *rr++ = w9;
  *rr++ = w14;
  /* #64: @9 = dot(@23, @28) */
  w9 = casadi_dot(2, w23, w28);
  /* #65: @4 = (@4*@9) */
  w4 *= w9;
  /* #66: @3 = (@3-@4) */
  w3 -= w4;
  /* #67: output[0][0] = @3 */
  if (res[0]) res[0][0] = w3;
  /* #68: @26 = zeros(6x1) */
  casadi_clear(w26, 6);
  /* #69: @27 = @27' */
  /* #70: @28 = zeros(1x2) */
  casadi_clear(w28, 2);
  /* #71: @24 = @24' */
  /* #72: @30 = @29' */
  for (i=0, rr=w30, cs=w29; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #73: @28 = mac(@24,@30,@28) */
  for (i=0, rr=w28; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w24+j, tt=w30+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #74: @28 = @28' */
  /* #75: @27 = (@27+@28) */
  for (i=0, rr=w27, cs=w28; i<2; ++i) (*rr++) += (*cs++);
  /* #76: @3 = dot(@23, @27) */
  w3 = casadi_dot(2, w23, w27);
  /* #77: @27 = (@3*@23) */
  for (i=0, rr=w27, cs=w23; i<2; ++i) (*rr++)  = (w3*(*cs++));
  /* #78: @28 = zeros(2x1) */
  casadi_clear(w28, 2);
  /* #79: @31 = @7' */
  for (i=0, rr=w31, cs=w7; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #80: @5 = @5' */
  /* #81: @24 = zeros(1x2) */
  casadi_clear(w24, 2);
  /* #82: @6 = @6' */
  /* #83: @32 = @25' */
  for (i=0, rr=w32, cs=w25; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #84: @24 = mac(@6,@32,@24) */
  for (i=0, rr=w24; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w6+j, tt=w32+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #85: @24 = @24' */
  /* #86: @5 = (@5+@24) */
  for (i=0, rr=w5, cs=w24; i<2; ++i) (*rr++) += (*cs++);
  /* #87: @28 = mac(@31,@5,@28) */
  for (i=0, rr=w28; i<1; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w31+j, tt=w5+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #88: @27 = (@27+@28) */
  for (i=0, rr=w27, cs=w28; i<2; ++i) (*rr++) += (*cs++);
  /* #89: @27 = (-@27) */
  for (i=0, rr=w27, cs=w27; i<2; ++i) *rr++ = (- *cs++ );
  /* #90: (@26[:2] += @27) */
  for (rr=w26+0, ss=w27; rr!=w26+2; rr+=1) *rr += *ss++;
  /* #91: {@3, @4, @9, @14, @16, @0} = vertsplit(@26) */
  w3 = w26[0];
  w4 = w26[1];
  w9 = w26[2];
  w14 = w26[3];
  w16 = w26[4];
  w0 = w26[5];
  /* #92: output[1][0] = @3 */
  if (res[1]) res[1][0] = w3;
  /* #93: output[1][1] = @4 */
  if (res[1]) res[1][1] = w4;
  /* #94: @4 = cos(@1) */
  w4 = cos( w1 );
  /* #95: @3 = -0.01 */
  w3 = -1.0000000000000000e-02;
  /* #96: @27 = (@3*@23) */
  for (i=0, rr=w27, cs=w23; i<2; ++i) (*rr++)  = (w3*(*cs++));
  /* #97: {@3, @17} = vertsplit(@27) */
  w3 = w27[0];
  w17 = w27[1];
  /* #98: @18 = (@10*@17) */
  w18  = (w10*w17);
  /* #99: @19 = (@4*@18) */
  w19  = (w4*w18);
  /* #100: @20 = sin(@1) */
  w20 = sin( w1 );
  /* #101: @21 = (@11*@17) */
  w21  = (w11*w17);
  /* #102: @33 = (@20*@21) */
  w33  = (w20*w21);
  /* #103: @19 = (@19-@33) */
  w19 -= w33;
  /* #104: @33 = cos(@1) */
  w33 = cos( w1 );
  /* #105: @11 = (@11*@3) */
  w11 *= w3;
  /* #106: @34 = (@33*@11) */
  w34  = (w33*w11);
  /* #107: @19 = (@19-@34) */
  w19 -= w34;
  /* #108: @34 = sin(@1) */
  w34 = sin( w1 );
  /* #109: @10 = (@10*@3) */
  w10 *= w3;
  /* #110: @35 = (@34*@10) */
  w35  = (w34*w10);
  /* #111: @19 = (@19-@35) */
  w19 -= w35;
  /* #112: @19 = (@19+@9) */
  w19 += w9;
  /* #113: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #114: @19 = (@19-@2) */
  w19 -= w2;
  /* #115: output[1][2] = @19 */
  if (res[1]) res[1][2] = w19;
  /* #116: @13 = (@13*@17) */
  w13 *= w17;
  /* #117: @8 = (@8*@3) */
  w8 *= w3;
  /* #118: @13 = (@13+@8) */
  w13 += w8;
  /* #119: @13 = (@13+@14) */
  w13 += w14;
  /* #120: output[1][3] = @13 */
  if (res[1]) res[1][3] = w13;
  /* #121: @15 = (@15*@17) */
  w15 *= w17;
  /* #122: @12 = (@12*@3) */
  w12 *= w3;
  /* #123: @15 = (@15-@12) */
  w15 -= w12;
  /* #124: @15 = (@15+@16) */
  w15 += w16;
  /* #125: output[1][4] = @15 */
  if (res[1]) res[1][4] = w15;
  /* #126: output[1][5] = @0 */
  if (res[1]) res[1][5] = w0;
  /* #127: @36 = zeros(6x6,9nz) */
  casadi_clear(w36, 9);
  /* #128: @26 = zeros(6x1) */
  casadi_clear(w26, 6);
  /* #129: @27 = zeros(1x2) */
  casadi_clear(w27, 2);
  /* #130: @0 = project(@23) */
  casadi_sparsify(w23, (&w0), casadi_s1, 0);
  /* #131: @37 = ones(6x1,3nz) */
  casadi_fill(w37, 3, 1.);
  /* #132: {@15, NULL, @16, NULL, NULL, NULL} = vertsplit(@37) */
  w15 = w37[0];
  w16 = w37[1];
  /* #133: @12 = @15[0] */
  for (rr=(&w12), ss=(&w15)+0; ss!=(&w15)+1; ss+=1) *rr++ = *ss;
  /* #134: @12 = (-@12) */
  w12 = (- w12 );
  /* #135: @15 = dot(@0, @12) */
  w15 = casadi_dot(1, (&w0), (&w12));
  /* #136: @28 = (@23*@15) */
  for (i=0, rr=w28, cr=w23; i<2; ++i) (*rr++)  = ((*cr++)*w15);
  /* #137: @5 = @28' */
  casadi_copy(w28, 2, w5);
  /* #138: @27 = mac(@5,@29,@27) */
  for (i=0, rr=w27; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w5+j, tt=w29+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #139: @27 = @27' */
  /* #140: @5 = zeros(1x2) */
  casadi_clear(w5, 2);
  /* #141: @28 = @28' */
  /* #142: @5 = mac(@28,@30,@5) */
  for (i=0, rr=w5; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w28+j, tt=w30+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #143: @5 = @5' */
  /* #144: @27 = (@27+@5) */
  for (i=0, rr=w27, cs=w5; i<2; ++i) (*rr++) += (*cs++);
  /* #145: @15 = dot(@23, @27) */
  w15 = casadi_dot(2, w23, w27);
  /* #146: @27 = (@23*@15) */
  for (i=0, rr=w27, cr=w23; i<2; ++i) (*rr++)  = ((*cr++)*w15);
  /* #147: @5 = zeros(2x1) */
  casadi_clear(w5, 2);
  /* #148: @28 = zeros(1x2) */
  casadi_clear(w28, 2);
  /* #149: @24 = zeros(2x1) */
  casadi_clear(w24, 2);
  /* #150: @24 = mac(@7,@12,@24) */
  casadi_mtimes(w7, casadi_s3, (&w12), casadi_s1, w24, casadi_s2, w, 0);
  /* #151: @6 = @24' */
  casadi_copy(w24, 2, w6);
  /* #152: @28 = mac(@6,@25,@28) */
  for (i=0, rr=w28; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w6+j, tt=w25+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #153: @28 = @28' */
  /* #154: @6 = zeros(1x2) */
  casadi_clear(w6, 2);
  /* #155: @24 = @24' */
  /* #156: @6 = mac(@24,@32,@6) */
  for (i=0, rr=w6; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w24+j, tt=w32+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #157: @6 = @6' */
  /* #158: @28 = (@28+@6) */
  for (i=0, rr=w28, cs=w6; i<2; ++i) (*rr++) += (*cs++);
  /* #159: @5 = mac(@31,@28,@5) */
  for (i=0, rr=w5; i<1; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w31+j, tt=w28+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #160: @27 = (@27+@5) */
  for (i=0, rr=w27, cs=w5; i<2; ++i) (*rr++) += (*cs++);
  /* #161: @27 = (-@27) */
  for (i=0, rr=w27, cs=w27; i<2; ++i) *rr++ = (- *cs++ );
  /* #162: (@26[:2] += @27) */
  for (rr=w26+0, ss=w27; rr!=w26+2; rr+=1) *rr += *ss++;
  /* #163: {@12, @15, @0, @13, @14, @8} = vertsplit(@26) */
  w12 = w26[0];
  w15 = w26[1];
  w0 = w26[2];
  w13 = w26[3];
  w14 = w26[4];
  w8 = w26[5];
  /* #164: @19 = cos(@1) */
  w19 = cos( w1 );
  /* #165: @19 = (@19*@16) */
  w19 *= w16;
  /* #166: @21 = (@21*@19) */
  w21 *= w19;
  /* #167: @21 = (-@21) */
  w21 = (- w21 );
  /* #168: @19 = sin(@1) */
  w19 = sin( w1 );
  /* #169: @19 = (@19*@16) */
  w19 *= w16;
  /* #170: @18 = (@18*@19) */
  w18 *= w19;
  /* #171: @21 = (@21-@18) */
  w21 -= w18;
  /* #172: @18 = sin(@1) */
  w18 = sin( w1 );
  /* #173: @18 = (@18*@16) */
  w18 *= w16;
  /* #174: @11 = (@11*@18) */
  w11 *= w18;
  /* #175: @21 = (@21+@11) */
  w21 += w11;
  /* #176: @11 = cos(@1) */
  w11 = cos( w1 );
  /* #177: @11 = (@11*@16) */
  w11 *= w16;
  /* #178: @10 = (@10*@11) */
  w10 *= w11;
  /* #179: @21 = (@21-@10) */
  w21 -= w10;
  /* #180: @21 = (@21+@0) */
  w21 += w0;
  /* #181: @0 = (-@16) */
  w0 = (- w16 );
  /* #182: @0 = (2.*@0) */
  w0 = (2.* w0 );
  /* #183: @21 = (@21-@0) */
  w21 -= w0;
  /* #184: @0 = cos(@1) */
  w0 = cos( w1 );
  /* #185: @0 = (@0*@16) */
  w0 *= w16;
  /* #186: @0 = (@17*@0) */
  w0  = (w17*w0);
  /* #187: @10 = sin(@1) */
  w10 = sin( w1 );
  /* #188: @10 = (@10*@16) */
  w10 *= w16;
  /* #189: @10 = (@3*@10) */
  w10  = (w3*w10);
  /* #190: @0 = (@0-@10) */
  w0 -= w10;
  /* #191: @0 = (@0+@13) */
  w0 += w13;
  /* #192: @13 = cos(@1) */
  w13 = cos( w1 );
  /* #193: @13 = (@13*@16) */
  w13 *= w16;
  /* #194: @13 = (@3*@13) */
  w13  = (w3*w13);
  /* #195: @13 = (-@13) */
  w13 = (- w13 );
  /* #196: @1 = sin(@1) */
  w1 = sin( w1 );
  /* #197: @1 = (@1*@16) */
  w1 *= w16;
  /* #198: @1 = (@17*@1) */
  w1  = (w17*w1);
  /* #199: @13 = (@13-@1) */
  w13 -= w1;
  /* #200: @13 = (@13+@14) */
  w13 += w14;
  /* #201: @26 = vertcat(@12, @15, @21, @0, @13, @8) */
  rr=w26;
  *rr++ = w12;
  *rr++ = w15;
  *rr++ = w21;
  *rr++ = w0;
  *rr++ = w13;
  *rr++ = w8;
  /* #202: @38 = @26[:5] */
  for (rr=w38, ss=w26+0; ss!=w26+5; ss+=1) *rr++ = *ss;
  /* #203: (@36[0, 1, 4, 5, 6] = @38) */
  for (cii=casadi_s4, rr=w36, ss=w38; cii!=casadi_s4+5; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #204: @38 = @26[:5] */
  for (rr=w38, ss=w26+0; ss!=w26+5; ss+=1) *rr++ = *ss;
  /* #205: (@36[0, 2, 4, 7, 8] = @38) */
  for (cii=casadi_s5, rr=w36, ss=w38; cii!=casadi_s5+5; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #206: @26 = zeros(6x1) */
  casadi_clear(w26, 6);
  /* #207: @27 = zeros(1x2) */
  casadi_clear(w27, 2);
  /* #208: @12 = project(@23) */
  casadi_sparsify(w23, (&w12), casadi_s6, 0);
  /* #209: @37 = ones(6x1,3nz) */
  casadi_fill(w37, 3, 1.);
  /* #210: {NULL, @15, NULL, @21, @0, NULL} = vertsplit(@37) */
  w15 = w37[0];
  w21 = w37[1];
  w0 = w37[2];
  /* #211: @13 = @15[0] */
  for (rr=(&w13), ss=(&w15)+0; ss!=(&w15)+1; ss+=1) *rr++ = *ss;
  /* #212: @13 = (-@13) */
  w13 = (- w13 );
  /* #213: @15 = dot(@12, @13) */
  w15 = casadi_dot(1, (&w12), (&w13));
  /* #214: @5 = (@23*@15) */
  for (i=0, rr=w5, cr=w23; i<2; ++i) (*rr++)  = ((*cr++)*w15);
  /* #215: @28 = @5' */
  casadi_copy(w5, 2, w28);
  /* #216: @27 = mac(@28,@29,@27) */
  for (i=0, rr=w27; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w28+j, tt=w29+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #217: @27 = @27' */
  /* #218: @28 = zeros(1x2) */
  casadi_clear(w28, 2);
  /* #219: @5 = @5' */
  /* #220: @28 = mac(@5,@30,@28) */
  for (i=0, rr=w28; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w5+j, tt=w30+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #221: @28 = @28' */
  /* #222: @27 = (@27+@28) */
  for (i=0, rr=w27, cs=w28; i<2; ++i) (*rr++) += (*cs++);
  /* #223: @15 = dot(@23, @27) */
  w15 = casadi_dot(2, w23, w27);
  /* #224: @23 = (@23*@15) */
  for (i=0, rr=w23; i<2; ++i) (*rr++) *= w15;
  /* #225: @27 = zeros(2x1) */
  casadi_clear(w27, 2);
  /* #226: @28 = zeros(1x2) */
  casadi_clear(w28, 2);
  /* #227: @5 = zeros(2x1) */
  casadi_clear(w5, 2);
  /* #228: @5 = mac(@7,@13,@5) */
  casadi_mtimes(w7, casadi_s3, (&w13), casadi_s6, w5, casadi_s2, w, 0);
  /* #229: @6 = @5' */
  casadi_copy(w5, 2, w6);
  /* #230: @28 = mac(@6,@25,@28) */
  for (i=0, rr=w28; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w6+j, tt=w25+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #231: @28 = @28' */
  /* #232: @6 = zeros(1x2) */
  casadi_clear(w6, 2);
  /* #233: @5 = @5' */
  /* #234: @6 = mac(@5,@32,@6) */
  for (i=0, rr=w6; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w5+j, tt=w32+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #235: @6 = @6' */
  /* #236: @28 = (@28+@6) */
  for (i=0, rr=w28, cs=w6; i<2; ++i) (*rr++) += (*cs++);
  /* #237: @27 = mac(@31,@28,@27) */
  for (i=0, rr=w27; i<1; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w31+j, tt=w28+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #238: @23 = (@23+@27) */
  for (i=0, rr=w23, cs=w27; i<2; ++i) (*rr++) += (*cs++);
  /* #239: @23 = (-@23) */
  for (i=0, rr=w23, cs=w23; i<2; ++i) *rr++ = (- *cs++ );
  /* #240: (@26[:2] += @23) */
  for (rr=w26+0, ss=w23; rr!=w26+2; rr+=1) *rr += *ss++;
  /* #241: {@13, @15, @12, @8, @14, @1} = vertsplit(@26) */
  w13 = w26[0];
  w15 = w26[1];
  w12 = w26[2];
  w8 = w26[3];
  w14 = w26[4];
  w1 = w26[5];
  /* #242: @16 = (@17*@21) */
  w16  = (w17*w21);
  /* #243: @4 = (@4*@16) */
  w4 *= w16;
  /* #244: @17 = (@17*@0) */
  w17 *= w0;
  /* #245: @20 = (@20*@17) */
  w20 *= w17;
  /* #246: @4 = (@4-@20) */
  w4 -= w20;
  /* #247: @0 = (@3*@0) */
  w0  = (w3*w0);
  /* #248: @33 = (@33*@0) */
  w33 *= w0;
  /* #249: @4 = (@4-@33) */
  w4 -= w33;
  /* #250: @3 = (@3*@21) */
  w3 *= w21;
  /* #251: @34 = (@34*@3) */
  w34 *= w3;
  /* #252: @4 = (@4-@34) */
  w4 -= w34;
  /* #253: @4 = (@4+@12) */
  w4 += w12;
  /* #254: @26 = vertcat(@13, @15, @4, @8, @14, @1) */
  rr=w26;
  *rr++ = w13;
  *rr++ = w15;
  *rr++ = w4;
  *rr++ = w8;
  *rr++ = w14;
  *rr++ = w1;
  /* #255: @23 = @26[:2] */
  for (rr=w23, ss=w26+0; ss!=w26+2; ss+=1) *rr++ = *ss;
  /* #256: (@36[2:4] = @23) */
  for (rr=w36+2, ss=w23; rr!=w36+4; rr+=1) *rr = *ss++;
  /* #257: @23 = @26[:2] */
  for (rr=w23, ss=w26+0; ss!=w26+2; ss+=1) *rr++ = *ss;
  /* #258: (@36[1:5:2] = @23) */
  for (rr=w36+1, ss=w23; rr!=w36+5; rr+=2) *rr = *ss++;
  /* #259: @39 = @36' */
  casadi_trans(w36,casadi_s7, w39, casadi_s7, iw);
  /* #260: output[2][0] = @39 */
  casadi_copy(w39, 9, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int USV_ode_cost_ext_cost_e_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int USV_ode_cost_ext_cost_e_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int USV_ode_cost_ext_cost_e_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void USV_ode_cost_ext_cost_e_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int USV_ode_cost_ext_cost_e_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void USV_ode_cost_ext_cost_e_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void USV_ode_cost_ext_cost_e_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void USV_ode_cost_ext_cost_e_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int USV_ode_cost_ext_cost_e_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int USV_ode_cost_ext_cost_e_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real USV_ode_cost_ext_cost_e_fun_jac_hess_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* USV_ode_cost_ext_cost_e_fun_jac_hess_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* USV_ode_cost_ext_cost_e_fun_jac_hess_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* USV_ode_cost_ext_cost_e_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s8;
    case 1: return casadi_s9;
    case 2: return casadi_s9;
    case 3: return casadi_s10;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* USV_ode_cost_ext_cost_e_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s11;
    case 1: return casadi_s8;
    case 2: return casadi_s7;
    case 3: return casadi_s9;
    case 4: return casadi_s12;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int USV_ode_cost_ext_cost_e_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 18;
  if (sz_res) *sz_res = 11;
  if (sz_iw) *sz_iw = 7;
  if (sz_w) *sz_w = 106;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
